# Round 4, batch 1: document corrections (category A) and decisions (category B)
# Slugs: anti-malarials, altitude-sickness, travellers-diarrhoea, dengue, yellow-fever,
# tetanus, junior-travel, typhoid, travel-core, hep-ab-travel, hep-b-occupational,
# japanese-encephalitis, rabies, meningitis-acwy-travel, meningitis-b, chickenpox,
# mmr, pneumococcal.
# Anchors verified against the masters in masters_r3.json with dump.py / apply_edits.
# Where an anchor text occurs more than once, nth is given, or every occurrence is intended
# (identical rows in two arms). Where several occurrences are replaced one by one, the nth
# values run in descending order so that each refers to the original document.

VACCINE_FOLLOW_UP = (
    "Attend for any further dose of the course on the date given. Seek medical advice for a severe or "
    "persistent injection site reaction, a fever that does not settle within 48 hours, or any sign of an "
    "allergic reaction. Call 999 for difficulty breathing, swelling of the face or throat, or collapse."
)

EDITS = {
    "anti-malarials": {
        "edits": [
            # Arm 3: the short cardiac bullet duplicates the fuller QT/conduction bullet in the same list
            ("delete", "Known cardiac conduction disorder, or a family history of one."),
            # Arm 2 (doxycycline) records row copied from Arm 1: doxycycline is not weight based
            # Arm 3 (mefloquine) records row: the mefloquine bands run to 45kg, not 40kg
            ("replace", "BODY WEIGHT in kilograms for every patient under 40kg, and the weight band applied.",
             "BODY WEIGHT in kilograms for every patient of 45kg or under, and the weight band applied.", 3),
            ("replace", "BODY WEIGHT in kilograms for every patient under 40kg, and the weight band applied.",
             "Age (12 years and over). Doxycycline dosing under this arm is not weight based; record body weight where it was used to consider an alternative agent.", 2),
            # Arms 2 and 3 records rows repeat the Malarone strength sentence, which does not apply to them
            ("replace", "Name, form and STRENGTH of the product supplied. Malarone and Malarone Paediatric are different strengths and both must be recorded by name.",
             "Name, form and strength of the product supplied (mefloquine 250mg tablets), including the brand, and whether the tablet supplied is scored where a divided dose is given.", 3),
            ("replace", "Name, form and STRENGTH of the product supplied. Malarone and Malarone Paediatric are different strengths and both must be recorded by name.",
             "Name, form and strength of the product supplied (doxycycline 100mg capsules), including the brand.", 2),
            # Change history table: the first v004 bullet is printed twice
            ("delete_contains", "The practitioner Agreement to practise page, the premises block and the practitioner signature table are restored.", None, 2),
            # Guidance summary: say that the pregnancy advice summarised is not authorised under this PGD
            ("insert_after_contains", "Women who have taken mefloquine or atovaquone-proguanil inadvertently just before or during the first trimester", [
                "Note for this PGD: pregnancy and breastfeeding are exclusions in all three arms of this PGD. The UKMEAG advice above on doxycycline before 15 weeks, on mefloquine and on atovaquone-proguanil in pregnancy is summarised for completeness only; chemoprophylaxis in pregnancy is a referral, not a supply under this PGD.",
            ]),
        ],
        "changes": [
            "The duplicate cardiac conduction bullet in the mefloquine arm's exclusion list was removed; the fuller QT prolongation and conduction disorder exclusion remains.",
            "The doxycycline arm's records row no longer asks for a weight band, because doxycycline dosing under this PGD is not weight based; the mefloquine arm's records row now covers patients of 45kg or under, matching its dose bands.",
            "The records rows of the doxycycline and mefloquine arms name their own product instead of repeating the Malarone strength sentence from the atovaquone with proguanil arm.",
            "The duplicated first bullet in the change history table was removed.",
            "The guidance summary now states that its pregnancy advice is not authorised under this PGD, which excludes pregnancy and breastfeeding in every arm.",
        ],
    },
    "altitude-sickness": {
        "edits": [
            ("replace_contains", "These are emergency situations",
             "These are emergency situations: urgent medical attention and descent are critical. Dexamethasone and nifedipine are not supplied under this PGD; they are listed so that the practitioner recognises the emergency and directs the patient to urgent medical care."),
            ("replace", "Prevention: maximum 14 days per supply without review. Treatment: maximum 3 days.",
             "Prevention: maximum 14 days per supply without review. Treatment: maximum 3 days (6 tablets). A treatment course supplied alongside a prevention course is a standby course: it is taken only if symptoms develop, for no more than 3 days, and no further treatment supply is made under this PGD without review."),
            ("replace", "date of supply dose, form and route quantity supplied",
             "date of supply, dose, form and route, quantity supplied, batch number and expiry date"),
            ("replace", "details of any adverse drug reactions and actions taken supplied via PGD",
             "details of any adverse drug reactions and the actions taken, and that the supply was made under this PGD"),
        ],
        "changes": [
            "The guidance summary now states that dexamethasone and nifedipine are not supplied under this PGD and are listed only so the emergency is recognised.",
            "The maximum treatment period row now says that a treatment course supplied with prevention is a standby course, taken only if symptoms develop and for no more than 3 days.",
            "The records row has its punctuation restored and now asks for the batch number and expiry date.",
        ],
    },
    "travellers-diarrhoea": {
        "edits": [
            ("replace_contains", "Azithromycin is indicated for the treatment of moderate to severe traveller",
             "Azithromycin is indicated for the treatment of moderate to severe traveller's diarrhoea, particularly when caused by likely bacterial pathogens and where fluoroquinolone resistance is a concern. Supply is normally made at a pre-travel consultation as a standby course, for the traveller to start only if moderate to severe symptoms develop during travel."),
            ("replace_contains", "Symptoms lasting more than 72 hours without improvement.",
             "- Known allergy to azithromycin or other macrolide antibiotics.\n- Severe liver disease or significant hepatic dysfunction.\n- Concomitant medications known to prolong the QT interval.\n- Bloody diarrhoea, high fever, or signs of systemic illness.\n- Current symptoms that have lasted more than 72 hours without improvement: refer, do not supply. A standby course is not for a patient who is already unwell."),
            ("replace", "Azithromycin", "Azithromycin 500 mg tablets.", 2),
            ("replace", "date of supply dose, form and route quantity supplied",
             "date of supply, dose, form and route, quantity supplied, batch number and expiry date"),
            ("replace", "details of any adverse drug reactions and actions taken supplied via PGD",
             "details of any adverse drug reactions and the actions taken, and that the supply was made under this PGD"),
            ("replace_contains", "do not improve in 3",
             "Start the course only if moderate to severe diarrhoea develops during travel (three or more loose stools in 24 hours with distressing symptoms). Seek local medical help urgently for blood in the stool, fever, severe abdominal pain, persistent vomiting or inability to keep fluids down, or if symptoms have not improved within 24 to 72 hours of starting azithromycin. Seek medical advice for any diarrhoea lasting more than 14 days, and on return if symptoms persist."),
        ],
        "changes": [
            "The indication now states that the supply is normally a standby course made at a pre-travel consultation, matching the inclusion criteria and the guidance summary.",
            "The 72 hour exclusion now reads as a supply exclusion: a patient who is already unwell for more than 72 hours without improvement is referred, not supplied.",
            "The name, form and strength row now states azithromycin 500 mg tablets, as Schedule 16 requires.",
            "The records row has its punctuation restored and now asks for the batch number and expiry date.",
            "The follow-up advice row, which carried the skin infection template wording about 3 to 4 weeks, now gives the self-start and when-to-seek-help advice appropriate to a 3 day standby course.",
        ],
    },
    "dengue": {
        "edits": [
            ("replace_contains", "for the treatment of Dengue Fever Prevention",
             "Patient Group Direction\nfor the administration of Qdenga (TAK-003) for the prevention of Dengue Fever"),
            ("replace", "for the treatment of", "for the prevention of"),
            ("replace", "Dengue Fever Prevention", "Dengue Fever"),
            ("replace", "Vaccination series over 3 months (with optional booster after 12 months based on ongoing exposure risk)",
             "Two doses 3 months apart complete the course. No booster dose is authorised under this PGD; the need for a booster has not been established (SmPC)."),
            ("delete", "Live vaccine: contraindicated in any immune deficiency"),
            ("replace", "date of supply dose, form and route quantity supplied",
             "date of administration, dose, form, route and anatomical site, quantity administered, batch number and expiry date"),
            ("replace", "details of any adverse drug reactions and actions taken supplied via PGD",
             "details of any adverse drug reactions and the actions taken, and that the vaccine was administered under this PGD"),
            ("replace", "Where the individual is UNDER 16, valid consent must come from a person with PARENTAL RESPONSIBILITY, or from the young person where you assess them as GILLICK COMPETENT.",
             "This PGD is restricted to adults aged 18 years and over, so consent from a person with parental responsibility or on the basis of Gillick competence does not arise. Anyone under 18 is excluded; record the advice given."),
            ("delete", "Record which of the two applied. Where consent was given by a person with parental responsibility, record their name and relationship to the patient. Where the young person consented on the basis of Gillick competence, record the basis of that assessment."),
            ("delete", "A parent accompanying a child does not automatically hold parental responsibility. Ask."),
            ("delete", "Users must be competent in assessing consent in children and young people before working under this PGD."),
        ],
        "changes": [
            "The title and cover now say the vaccine is for the prevention of dengue fever, not 'the treatment of Dengue Fever Prevention'.",
            "The maximum treatment period row no longer mentions an optional booster, which had no dose row, no inclusion criterion and no SmPC basis; two doses 3 months apart complete the course and no booster is authorised.",
            "The third repetition of the live vaccine immune deficiency statement in the cautions row was removed; the exclusion and the first caution remain.",
            "The records row has its punctuation restored and now asks for the anatomical site, batch number and expiry date.",
            "The consent in children and young people block now states that it does not apply, because this PGD excludes anyone under 18.",
        ],
    },
    "yellow-fever": {
        "edits": [
            ("insert_after", "A single 0.5 ml dose is given subcutaneously after reconstitution with the supplied solvent, and used immediately.", [
                "Age: the vaccine is contraindicated under 6 months, is considered at 6 to 8 months only on specialist advice where the risk is high and travel unavoidable, and is given routinely from 9 months. The lower age limit under this PGD is 9 months.",
            ]),
            ("delete", "batch number, expiry date and anatomical site of administration"),
            ("replace", "The requirements on the following pages form part of this Patient Group Direction and must be met before any vaccine is administered under it. They were absent from the signed document and were added by this reissue after an estate-wide safety sweep of every vaccination PGD.",
             "The requirements on the following pages form part of this Patient Group Direction and must be met before any vaccine is administered under it."),
            ("replace", "This reissue adds the safety requirements below and changes nothing else. It is NOT a clinical review of this PGD, and one remains outstanding.",
             "These requirements were added at version 002 and have been carried forward through the clinical reviews of versions 003 and 004."),
        ],
        "changes": [
            "The guidance summary now states the age floor: contraindicated under 6 months, specialist advice only at 6 to 8 months, routine from 9 months, which is the lower age limit of this PGD.",
            "The duplicate 'batch number, expiry date and anatomical site' line in the records row was removed; both items remain in the list.",
            "The introduction to the vaccine safety block no longer says that a clinical review remains outstanding; versions 003 and 004 were clinical reviews.",
        ],
    },
    "tetanus": {
        "edits": [
            ("replace", "Three changes in this version", "Key rules in this version"),
            ("replace", "Where the person is NOT adequately primed (fewer than 5 documented doses) or the vaccination history is uncertain, and the wound is tetanus-prone: give the vaccine dose under this PGD AND refer the same day for tetanus immunoglobulin, whether or not the wound is high risk. Where the person is adequately primed but the last dose was more than 10 years ago and the wound is HIGH RISK: give the reinforcing dose AND refer the same day for immunoglobulin. This follows Green Book chapter 30, table 30.1.",
             "Where the person is NOT adequately primed (fewer than 3 documented doses of a primary course) or the vaccination history is uncertain, and the wound is tetanus-prone: give the vaccine dose under this PGD AND refer the same day for tetanus immunoglobulin, whether or not the wound is high risk. Where the person is adequately primed but the last dose was more than 10 years ago and the wound is HIGH RISK: give the reinforcing dose AND refer the same day for immunoglobulin. This follows UKHSA Tetanus: advice for health professionals (Table 4), which governs wound management while Green Book chapter 30 is updated."),
            ("replace", "All users must be able to apply Green Book chapter 30 table 30.1 to a tetanus-prone wound, and must know that a decision about tetanus immunoglobulin is a referral and not a PGD supply.",
             "All users must be able to apply UKHSA Tetanus: advice for health professionals (Table 4), which governs tetanus-prone wound management while Green Book chapter 30 is updated, and must know that a decision about tetanus immunoglobulin is a referral and not a PGD supply."),
            ("replace", "Where a wound is involved, the assessment against Green Book chapter 30 table 30.1 and the conclusion on immunoglobulin.",
             "Where a wound is involved, the assessment against UKHSA Tetanus: advice for health professionals (Table 4) and the conclusion on immunoglobulin."),
            ("insert_after", "Revaxis Td/IPV, individuals aged 10 years and over, covering the adolescent booster, incomplete or unknown history, travel, and tetanus-prone wounds where immunoglobulin is not indicated.", [
                "003 to 007, September 2026: see the version and change record at the end of this document.",
            ]),
        ],
        "changes": [
            "The immunoglobulin rule now uses the same definition of adequate priming as the cover, the inclusion criteria, the dose row and Appendix 1: 3 or more documented primary doses (UKHSA Tetanus: advice for health professionals, Table 4). The previous wording said fewer than 5 documented doses, which contradicted the rest of the document.",
            "The immunoglobulin rule, the training row and the records row now cite UKHSA Tetanus: advice for health professionals (Table 4), which part 2 identifies as governing wound management while Green Book chapter 30 is updated, instead of table 30.1.",
            "The cover heading 'Three changes in this version', which sat above four bullets from earlier versions, now reads 'Key rules in this version'.",
            "The change history table's previous versions list now points to the version and change record for versions 003 to 007.",
        ],
    },
    "junior-travel": {
        "edits": [
            ("replace", "Valid informed consent not obtained, or no person with parental responsibility available to consent for a child under 16 who is not Gillick competent.",
             "Valid informed consent not obtained, or no person with parental responsibility (or a suitable adult authorised by them) present for a child under 16 years, whether or not the child is Gillick competent."),
            ("replace", "that valid informed consent was given by the individual, or by a person with parental responsibility, or that a decision was made in the individual’s best interests in accordance with the Mental Capacity Act 2005",
             "that valid informed consent was given, and by whom (see below)"),
            ("replace", "Nimenrix® from 12 months under this PGD; MenQuadfi® from 12 months",
             "Nimenrix® from 12 months under this PGD (licensed from 6 weeks); MenQuadfi® from 12 months"),
            ("replace", "No minimum age (12 months under this PGD)",
             "12 months under this PGD (licensed at all ages)"),
            # paediatric hepatitis presentations are licensed to 15 years inclusive; the PGD runs to 17
            ("replace", "12 months", "12 months to 15 years inclusive (paediatric presentation, licensed to 15 years; a 16 or 17 year old needs the adult presentation under the Hepatitis A and B travel PGD)", 3),
            ("replace", "12 months", "12 months to 15 years inclusive (paediatric presentation, licensed to 15 years; a 16 or 17 year old needs the adult presentation under the Hepatitis A and B travel PGD)", 2),
            ("replace", "12 months", "12 months to 15 years inclusive (paediatric presentation, licensed to 15 years; a 16 or 17 year old needs the adult presentation under the Hepatitis A and B travel PGD)", 1),
            ("replace", "12 months under this PGD (licensed from birth)",
             "12 months to 15 years inclusive under this PGD (paediatric presentation, licensed from birth to 15 years; a 16 or 17 year old needs the adult presentation under the Hepatitis A and B travel PGD)"),
        ],
        "changes": [
            "The exclusion on parental presence now says the same as the inclusion criterion: a person with parental responsibility, or a suitable adult authorised by them, must be present for every child under 16, whether or not the child is Gillick competent.",
            "The records row no longer carries the adult Mental Capacity Act best-interests wording, which cannot apply in a PGD limited to under-18s; consent and by whom is recorded as set out in the same row.",
            "The MenACWY row states the licensed minimum age for Nimenrix (6 weeks), and the rabies row uses the same form of words as the other rows.",
            "The Havrix Junior, Avaxim Junior, Twinrix Paediatric, Ambirix, Engerix B Paediatric and HBvaxPRO Paediatric rows now state that these paediatric presentations are licensed to 15 years inclusive, so a 16 or 17 year old needs the adult presentation under the Hepatitis A and B travel PGD. The previous rows had no upper age in a PGD covering up to 17 years.",
        ],
    },
    "typhoid": {
        "edits": [
            ("replace", "A dose of typhoid Vi vaccine within the last 3 years, unless the traveller is returning to a risk area and the previous dose is due for renewal. Record the previous dose date.",
             "A dose of typhoid Vi vaccine within the last 3 years. Record the previous dose date; the next dose is due 3 years after it."),
            ("replace", "Bleeding disorders or anticoagulation: use a fine needle (23 gauge or finer) and apply firm pressure without rubbing for at least 2 minutes.",
             "Bleeding disorders or anticoagulation: give intramuscularly with a fine needle (23 gauge or finer) and apply firm pressure without rubbing for at least 2 minutes (Green Book chapter 4). Deep subcutaneous injection is the alternative where the individual's haematologist or specialist advises it."),
            ("replace", "Intramuscular injection, 0.5 mL. Deltoid in adults and children aged 2 and over. Do not give intravascularly.",
             "Intramuscular injection, 0.5 mL, into the deltoid (every patient under this PGD is aged 2 years or over). Do not give intravascularly."),
            ("replace", "Records signed, dated, legible and contemporaneous. Adults: 8 years. Under 18s: until the 25th birthday.",
             "Records signed, dated, legible and contemporaneous. Adults: 8 years. Under 18s: until the 25th birthday, or the 26th where the individual was 17 when the dose was given."),
        ],
        "changes": [
            "The 3 year exclusion no longer carries the circular exception about a dose 'due for renewal', which could never be satisfied inside the 3 year window; a dose within the last 3 years excludes.",
            "The bleeding disorder caution now states the intramuscular fine needle technique with the Green Book chapter 4 reference and names deep subcutaneous injection as the alternative on specialist advice, so it agrees with the guidance summary.",
            "The route row states the deltoid without an age qualifier that excluded nobody.",
            "The retention row now carries the 26th birthday clause used in the other PGDs.",
        ],
    },
    "travel-core": {
        "edits": [
            ("replace_contains", "for the treatment of Travel Health",
             "Patient Group Direction\nfor the administration of Hepatitis A Vaccine (Havrix/Avaxim), Typhoid Vaccine (Typhim Vi), Cholera Vaccine (Dukoral) for the prevention of travel-related infection"),
            ("replace", "for the treatment of", "for protection against"),
            ("replace", "Travel Health", "Cholera (travel)", 3),
            ("replace", "Travel Health", "Typhoid (travel)", 2),
            ("replace", "Travel Health", "Hepatitis A (travel)", 1),
            ("replace", "High-risk groups: travelers to South Asia, Southeast Asia, Africa, or Central/South America",
             "High-risk destinations: South Asia, Southeast Asia, Africa, or Central/South America, confirmed against current NaTHNaC / TravelHealthPro country information"),
            ("replace", "Take on empty stomach with water; do not mix with other liquids",
             "Give as set out in the route row: buffer dissolved in about 150 mL of cool water with the whole vial added, and nothing to eat or drink, and no other oral medicines, for 1 hour before and 1 hour after"),
            ("replace", "Complete the full vaccination course as recommended (particularly for Cholera vaccine which requires 2 doses).",
             "Complete the full course recommended for the vaccine given: cholera, 2 doses at least 1 week apart, finished at least 1 week before exposure; hepatitis A, a second dose at 6 to 12 months for long-term protection."),
            ("replace", "date of supply dose, form and route quantity supplied",
             "date of administration, dose, form, route and anatomical site, quantity administered, batch number and expiry date"),
            ("replace", "details of any adverse drug reactions and actions taken supplied via PGD",
             "details of any adverse drug reactions and the actions taken, and that the vaccine was administered under this PGD"),
        ],
        "changes": [
            "The title and the three covers now say the vaccines are for protection against hepatitis A, typhoid and cholera, not 'for the treatment of Travel Health'.",
            "The typhoid inclusion criterion lists the high-risk regions as destinations, confirmed against NaTHNaC / TravelHealthPro, rather than as 'groups'.",
            "The Dukoral caution about taking it on an empty stomach with water now matches the route row (buffer in about 150 mL of water, nothing by mouth for 1 hour either side).",
            "The follow-up advice under all three vaccines now gives the course completion advice for the vaccine given, instead of the cholera sentence under every vaccine.",
            "The records rows have their punctuation restored and now ask for the anatomical site, batch number and expiry date.",
        ],
    },
    "hep-ab-travel": {
        "edits": [
            ("replace", "Valid informed consent obtained, from a person with parental responsibility where the patient is a child.",
             "Valid informed consent obtained: from the patient where aged 16 or over, and from a person with parental responsibility where the patient is under 16."),
            ("replace", "that valid informed consent was given, and by whom where the patient is a child",
             "that valid informed consent was given, and by whom where the patient is under 16"),
            ("replace", "Confirmed anaphylactic reaction to a previous dose of the same vaccine, or to any component. Havrix and Twinrix contain trace neomycin, so a neomycin allergy excludes them.",
             "Confirmed anaphylactic reaction to a previous dose of the same vaccine, or to any component. Havrix, Twinrix and Avaxim may contain trace neomycin, so a neomycin hypersensitivity excludes every hepatitis A containing product under this PGD."),
            ("replace", "Pregnancy. Hepatitis A vaccine may be given where clearly indicated. For Twinrix the SPC advises delaying until after delivery unless there is an urgent need to protect the mother against hepatitis B. Where hepatitis B protection is needed in pregnancy, use a monovalent hepatitis B vaccine and document the risk assessment.",
             "Pregnancy. Hepatitis A vaccine may be given where clearly indicated (Havrix preferred). Twinrix is not given in pregnancy under this PGD: where hepatitis B protection is needed in pregnancy, use a monovalent hepatitis B vaccine and document the risk assessment."),
            ("replace", "Six products are covered. Selecting the wrong strength for the age is the most likely error, because the paediatric formulations contain half the antigen of the adult ones and the packaging is similar.",
             "Eight products are covered: the six in the table below, and Avaxim and Avaxim Junior, which are set out in the Avaxim section at the end of this document. Selecting the wrong strength for the age is the most likely error, because the paediatric formulations contain half the antigen of the adult ones and the packaging is similar."),
            ("replace", "The patient should remain on the premises for observation in line with the pharmacy SOP.",
             "Observe every patient for 15 minutes after vaccination, seated, and record that the observation period was completed (see Observation after vaccination below)."),
            ("insert_after", "that the vaccine was administered via PGD", [
                "that the 15 minute observation period was completed",
            ]),
        ],
        "changes": [
            "The consent criterion and the records row now define the child: a patient aged 16 or over consents for themselves; under 16, consent comes from a person with parental responsibility.",
            "The neomycin sentence now covers Avaxim as well as Havrix and Twinrix, so a neomycin hypersensitivity excludes every hepatitis A containing product under this PGD.",
            "The pregnancy caution no longer leaves a case for Twinrix in pregnancy: where hepatitis B protection is needed, a monovalent hepatitis B vaccine is used.",
            "The products sentence now counts eight products and points to the Avaxim section added at version 003.",
            "The anaphylaxis and observation row now states the 15 minute seated observation that the safety block requires, and the records row asks for it to be recorded.",
        ],
    },
    "hep-b-occupational": {
        "edits": [
            ("insert_after", "Day 0, 7, and 21, with a booster at 12 months", [
                "The ultra-rapid (day 0, 7 and 21) schedule is not authorised under this PGD; only the standard and accelerated schedules in the dose rows are.",
            ]),
            ("replace", "Engerix B is indicated for the active immunisation of individuals at risk of exposure to hepatitis B virus, including healthcare workers, infants born to infected mothers, and individuals at occupational or lifestyle risk.",
             "Engerix B is indicated for the active immunisation of individuals at risk of exposure to hepatitis B virus. Under this PGD: individuals aged 16 years and over at occupational, travel or lifestyle risk, including healthcare workers. Infants born to infected mothers, and anyone under 16, are outside this PGD."),
            ("replace", "HBVax Pro is indicated for the active immunisation of individuals at risk of exposure to hepatitis B virus, including healthcare workers, infants born to infected mothers, and individuals at occupational or lifestyle risk.",
             "HBVax Pro is indicated for the active immunisation of individuals at risk of exposure to hepatitis B virus. Under this PGD: individuals aged 16 years and over at occupational, travel or lifestyle risk, including healthcare workers. Infants born to infected mothers, and anyone under 16, are outside this PGD."),
            ("replace_contains", "- Previous allergic reaction to any hepatitis B vaccine.",
             "- Known hypersensitivity to the active substance or any excipients.\n- Known hypersensitivity to yeast (both vaccines are produced in yeast and may contain traces of yeast protein).\n- Previous allergic reaction to any hepatitis B vaccine.\n- Aged under 16 years.\n- Acute severe febrile illness (postpone until recovered)."),
            ("replace_contains", "- Observe patient for 15 minutes post-vaccination.",
             "- Use with caution in individuals with bleeding disorders or on anticoagulants.\n- Observe every patient for 15 minutes after vaccination, seated, and record that the observation period was completed.\n- Ensure adherence to the complete vaccination schedule.\n- Provide follow-up advice and written patient information leaflet (PIL)."),
            ("replace_contains", "Typically 6",
             "A course of 3 doses over 6 months (standard schedule) or 4 doses over 12 months (accelerated schedule). Booster doses are not covered by this PGD."),
            ("replace", "date of supply dose, form and route quantity supplied",
             "date of administration, dose, form and route, quantity administered"),
            ("replace", "details of any adverse drug reactions and actions taken supplied via PGD",
             "details of any adverse drug reactions and the actions taken, and that the vaccine was administered under this PGD"),
            ("replace_contains", "do not improve in 3", VACCINE_FOLLOW_UP + " Post-vaccination serology 1 to 4 months after the final dose where occupational health requires it."),
            ("replace", "Where the individual is UNDER 16, valid consent must come from a person with PARENTAL RESPONSIBILITY, or from the young person where you assess them as GILLICK COMPETENT.",
             "This PGD excludes anyone under 16, so consent from a person with parental responsibility or on the basis of Gillick competence does not arise. A 16 or 17 year old may consent for themselves; assess capacity as for an adult."),
            ("delete", "Record which of the two applied. Where consent was given by a person with parental responsibility, record their name and relationship to the patient. Where the young person consented on the basis of Gillick competence, record the basis of that assessment."),
            ("delete", "A parent accompanying a child does not automatically hold parental responsibility. Ask."),
            ("delete", "Users must be competent in assessing consent in children and young people before working under this PGD."),
        ],
        "changes": [
            "The guidance summary now states that the ultra-rapid day 0, 7 and 21 schedule is not authorised under this PGD.",
            "Both indications now say who this PGD covers (16 years and over at occupational, travel or lifestyle risk) and that infants born to infected mothers and anyone under 16 are outside it.",
            "Known hypersensitivity to yeast, which both SmPCs name, is now an exclusion in both arms.",
            "Both cautions rows now require the 15 minute seated observation to be recorded, as the other vaccine PGDs do.",
            "The maximum treatment period rows now state the course (3 doses over 6 months or 4 doses over 12 months) instead of 'typically 6 to 12 months', and that boosters are not covered.",
            "The records rows have their punctuation restored, and the follow-up advice rows, which carried the treatment template about 3 to 4 weeks, now give vaccination follow-up advice including post-vaccination serology where occupational health requires it.",
            "The consent in children and young people block now states that it does not apply, because this PGD excludes anyone under 16.",
        ],
    },
    "japanese-encephalitis": {
        "edits": [
            ("replace", "Sufficient time before travel to complete the primary course, ideally with at least one week between the second dose and potential exposure.",
             "Sufficient time before travel to complete a primary course (the standard course, or the rapid course where the standard course cannot be completed in time, with off-label consent where the rapid course applies), ideally with at least one week between the second dose and potential exposure. Where even the rapid course cannot be completed before travel, refer."),
            ("replace", "Immunosuppression. An adequate immune response may not be achieved. Counsel accordingly and consider referral for serology where the risk is high.",
             "Immunosuppression. An adequate immune response may not be achieved (Ixiaro SPC section 4.4; the Green Book chapter gives no guidance on this group). Counsel accordingly and consider referral for serology where the risk is high."),
            ("replace", "Age over 65. Seroconversion is lower, around 65% compared with over 96% in adults under 50, and titres are lower. Counsel that protection may be less reliable and consider the booster at 12 months.",
             "Age over 65. Seroconversion is lower, around 65% compared with over 96% in adults under 50, and titres are lower (Ixiaro SPC section 5.1). Counsel that protection may be less reliable and consider the booster at 12 months."),
            ("replace", "The patient should remain on the premises for observation after vaccination in line with the pharmacy SOP.",
             "Observe every patient for 15 minutes after vaccination, seated, and record that the observation period was completed (see Observation after vaccination below)."),
            ("replace", "If the course is interrupted, resume it rather than restarting. A second dose given up to 11 months after the first still produces a high rate of seroconversion.",
             "If the course is interrupted, resume it rather than restarting. A second dose given up to 11 months after the first still produces a high rate of seroconversion (Ixiaro SPC section 5.1)."),
        ],
        "changes": [
            "The 'sufficient time before travel' inclusion criterion now says which course it refers to: the standard course, or the rapid course with off-label consent where the standard course cannot be completed in time, with referral where even the rapid course cannot be completed.",
            "The immunosuppression caution, the over-65 seroconversion figures and the 11 month second dose statement now cite the Ixiaro SPC sections they come from, since the Green Book summary in part 2 does not contain them.",
            "The anaphylaxis and observation row now states the 15 minute seated observation that the safety block requires, instead of 'in line with the pharmacy SOP'.",
        ],
    },
    "rabies": {
        "edits": [
            ("replace", "for the administration of Rabipur or Verorab (Rabies Vaccine) for the treatment of Pre-exposure Prophylaxis against Rabies",
             "for the administration of Rabipur or Verorab (Rabies Vaccine) for pre-exposure prophylaxis against rabies"),
            ("replace", "for the administration, for the treatment of Pre-exposure Prophylaxis against Rabies, of:",
             "for the administration, for pre-exposure prophylaxis against rabies, of:"),
            ("replace", "There is currently one rabies vaccine licensed for intramuscular use in the UK, purified chick embryo cell rabies vaccine (PCEC, 2.5 IU/mL), Rabipur. Rabies Vaccine BP (human diploid cell vaccine) from Sanofi was discontinued in 2022.",
             "The chapter states that there is currently one rabies vaccine licensed for intramuscular use in the UK, purified chick embryo cell rabies vaccine (PCEC, 2.5 IU/mL), Rabipur, and that Rabies Vaccine BP (human diploid cell vaccine) from Sanofi was discontinued in 2022. This is out of date: see the note below on Verorab, UK-licensed since November 2023."),
            ("replace", "All users must be competent in assessing consent in children and young people, including parental responsibility and Gillick competence. The conventional course under this PGD has no lower age limit, so children are in scope.",
             "All users must be competent in assessing consent in children and young people, including parental responsibility and Gillick competence. The conventional course under this PGD is available from 2 years of age, so children are in scope."),
            ("replace", "Any age for the CONVENTIONAL course. Both products are licensed in all age groups.",
             "Aged 2 years and over for the CONVENTIONAL course. Both products are licensed in all age groups; the 2 year floor is a Get Real Health service restriction."),
            ("replace", "Where the accelerated course is used, documented consent to off-label use. In a young person that consent must come from the person with parental responsibility as well.",
             "Where the accelerated course is used (18 years and over only), documented consent to off-label use."),
            ("insert_after", "Under 18 and the accelerated course is being requested. The conventional course may still be given.", [
                "Aged under 2 years. This is a Get Real Health service restriction; refer to the GP or a travel clinic.",
            ]),
            ("replace", "For Verorab specifically: hypersensitivity to polymyxin B, streptomycin or neomycin, or to any antibiotic of the same class.",
             "Hypersensitivity to neomycin excludes BOTH products: Rabipur contains traces of neomycin, chlortetracycline and amphotericin B, and Verorab may contain traces of polymyxin B, streptomycin and neomycin. For Verorab specifically: hypersensitivity to polymyxin B or streptomycin, or to any antibiotic of the same class."),
            ("replace_contains", "Intramuscular, into the deltoid in older children and adults, or the anterolateral thigh in infants and young children.",
             "Intramuscular, into the deltoid in older children and adults, or the anterolateral thigh in young children. Never into the buttock. For a patient with a bleeding disorder, give by deep subcutaneous injection instead. Reconstitute immediately before use. Rabipur must be used within one hour of reconstitution; Verorab for intramuscular use must be used immediately. Where given with other vaccines, use separate sites, preferably different limbs, or at least 2.5 cm apart, and record the site of each."),
        ],
        "changes": [
            "The age floor is now stated the same way throughout: 2 years and over for the conventional course (the cover already said so; the inclusion row, the training row and the route row said any age or mentioned infants). Under 2 years is now listed as an exclusion, stated as a Get Real Health service restriction.",
            "Neomycin hypersensitivity now excludes both products, since Rabipur contains trace neomycin as well as Verorab; the previous exclusion named Verorab only.",
            "The unreachable sentence requiring parental consent to the accelerated course in a young person was removed, because the accelerated course is restricted to 18 and over.",
            "The guidance summary now flags on its face that the chapter's statement that Rabipur is the only licensed vaccine is out of date, with a pointer to the Verorab note.",
            "The title and the cover no longer read 'for the treatment of Pre-exposure Prophylaxis'.",
        ],
    },
    "meningitis-acwy-travel": {
        "edits": [
            ("insert_after", "Outbreak or contact management, which is directed by the local UKHSA Health Protection Team and is outside a private travel PGD.", [
                "A MenACWY conjugate vaccine dose within the last 5 years, other than the 12 month booster of the infant Nimenrix schedule. A repeat dose is authorised only as set out under Repeat doses (previous dose more than 5 years ago and a certificate required); an at-risk individual who may need an earlier booster is referred.",
            ]),
            ("replace", "Second dose given in the second year of life.",
             "That booster is the second and final dose of the infant course, given in the second year of life."),
            ("replace", "Records signed, dated, legible and contemporaneous. Adults: 8 years. Under 18s: until the 25th birthday.",
             "Records signed, dated, legible and contemporaneous. Adults: 8 years. Under 18s: until the 25th birthday, or the 26th where the individual was 17 when the dose was given."),
        ],
        "changes": [
            "A dose within the last 5 years is now listed under the exclusion criteria, which is what the repeat doses row already implied; the repeat for a certificate after 5 years is unchanged.",
            "The Appendix 1 row for infants aged 6 to 11 months now says that the 12 month booster is the second and final dose of the infant course, rather than reading as a separate dose.",
            "The retention row now carries the 26th birthday clause used in the other PGDs.",
        ],
    },
    "meningitis-b": {
        "edits": [
            ("replace", "Requires protection against meningococcal group B disease: routine doses missed or presenting outside the NHS programme, an adolescent or student seeking protection, or an adult at increased risk.",
             "Requires protection against meningococcal group B disease: routine doses missed or presenting outside the NHS programme, an adolescent or student seeking protection, or an adult at increased risk (asplenia or splenic dysfunction, a complement disorder, complement inhibitor therapy, or laboratory work with Neisseria meningitidis)."),
            ("replace", "Asplenia, splenic dysfunction, complement disorders and complement inhibitor therapy: vaccinate, but see the timing requirements above regarding complement inhibitors and prophylactic antibiotics, and involve the specialist team.",
             "Asplenia, splenic dysfunction, complement disorders and complement inhibitor therapy: vaccinate, and involve the specialist team. An individual due to start a complement inhibitor should be vaccinated at least 2 weeks before treatment begins; where treatment starts sooner, prophylactic antibiotics are required until 2 weeks after vaccination, arranged by the specialist team (see the guidance summary in part 2)."),
            ("replace", "0.5 ml intramuscular. Anterolateral thigh in infants under 1 year, deltoid thereafter",
             "0.5 ml intramuscular. Anterolateral thigh for infants aged 1 year and under, deltoid for older children and adults"),
            ("replace", "Routine use: 2 doses at 0 and 6 months. Individuals at increased risk, or in an outbreak setting where advised: 3 doses at 0, 1 to 2 months, and 6 months.",
             "Routine use: 2 doses at 0 and 6 months. Individuals at increased risk (see inclusion criteria): 3 doses at 0, 1 to 2 months, and 6 months. Outbreak management is outside this PGD."),
            ("delete", "batch number, expiry date and anatomical site of administration"),
        ],
        "changes": [
            "The inclusion criterion now names the increased risk groups (asplenia or splenic dysfunction, complement disorders, complement inhibitor therapy, laboratory work with Neisseria meningitidis) that the indication and the guidance summary describe.",
            "The complement inhibitor caution now states the timing requirement itself instead of referring to 'the timing requirements above', which were in part 2.",
            "The Bexsero schedule table and the route row now give the same injection site rule: anterolateral thigh for infants aged 1 year and under, deltoid for older children and adults.",
            "The Trumenba 3 dose schedule no longer mentions an outbreak setting, which is an exclusion under this PGD.",
            "The duplicate 'batch number, expiry date and anatomical site' line in the records row was removed; both items remain in the list.",
        ],
    },
    "chickenpox": {
        "edits": [
            ("replace_contains", "for the administration of Varivax and Varilirix for vaccination against Chickenpox",
             "Patient Group Direction\nfor the administration of Varivax and Varilrix for vaccination against Chickenpox"),
            ("replace_contains", "for the administration of Varilrix for the treatment of Chickenpox",
             "Patient Group Direction\nfor the administration of Varilrix for vaccination against Chickenpox"),
            ("replace", "Varilirix", "Varilrix"),
            ("replace", "Typically administered subcutaneously, but intramuscular administration is also acceptable if necessary.",
             "Both vaccines are given subcutaneously. The route row of each arm of this PGD governs: Varivax by subcutaneous injection; Varilrix by subcutaneous or intramuscular injection."),
            ("replace", "One or two doses depending on immune status and age group.",
             "Two doses. The course is complete only after the second dose."),
            ("replace", "One or two doses depending on age and immune status.",
             "Two doses. The course is complete only after the second dose."),
            ("replace", "Two 0.5 mL doses. Varilrix: second dose at least 6 weeks after the first, and never less than 4 weeks.",
             "Two 0.5 mL doses. Varilrix: second dose preferably 6 weeks after the first, and never less than 4 weeks (SmPC). Record the reason where the interval is between 4 and 6 weeks."),
            ("replace", "date of supply dose, form and route quantity supplied",
             "date of administration, dose, form, route and anatomical site, quantity administered, batch number and expiry date"),
            ("replace", "details of any adverse drug reactions and actions taken supplied via PGD",
             "details of any adverse drug reactions and the actions taken, and that the vaccine was administered under this PGD"),
            ("replace_contains", "do not improve in 3",
             "Attend for the second dose on the date given. Seek medical advice for a severe or persistent injection site reaction, a fever that does not settle within 48 hours, a widespread vesicular rash, or any sign of an allergic reaction; call 999 for difficulty breathing, swelling of the face or throat, or collapse. Avoid salicylates (aspirin) for 6 weeks after each dose. While any vaccine-related rash is present, avoid close contact with pregnant women, newborn babies and people with weakened immunity."),
        ],
        "changes": [
            "The product name Varilrix was misspelt 'Varilirix' in the title, on the Varilrix cover and in its name of medicine row; corrected. The Varilrix cover no longer says 'for the treatment of Chickenpox'.",
            "The guidance summary's statement that intramuscular administration is acceptable for the vaccine generally now defers to the route row of each arm (Varivax subcutaneous; Varilrix subcutaneous or intramuscular).",
            "The maximum treatment period rows in both arms now say two doses, matching the dose rows and the version 003 change record; the previous 'one or two doses' wording contradicted them.",
            "The Varilrix interval now reads as the SmPC has it: preferably 6 weeks, never less than 4, with the reason recorded for an interval between 4 and 6 weeks.",
            "The records rows have their punctuation restored and ask for the site, batch number and expiry date; the follow-up advice rows, which carried the treatment template about 3 to 4 weeks, now give vaccination follow-up advice including salicylate avoidance and contact precautions for a vaccine rash.",
        ],
    },
    "mmr": {
        "edits": [
            ("replace", "MMRVaxPRO", "MMRVaxPRO, powder and solvent for suspension for injection, one 0.5 mL dose per vial"),
            ("replace", "MMRVaxPRO 5mg", "MMRVaxPRO"),
            ("replace", "Priorix", "Priorix, powder and solvent for solution for injection, one 0.5 mL dose per vial", 2),
            ("replace_contains", "Acute febrile illness (vaccination should be postponed).",
             "- Known hypersensitivity to neomycin, gelatin, or any other component of the vaccine, or anaphylaxis to a previous measles, mumps or rubella containing vaccine. Egg allergy, including previous anaphylaxis to egg, is NOT a contraindication to MMR (Green Book chapter 21) and is not an exclusion under this PGD.\n- Immunocompromised individuals or those receiving immunosuppressive therapy.\n- Blood dyscrasias, leukaemia, lymphoma or other malignant neoplasm of the haematopoietic or lymphatic system.\n- Family history of congenital or hereditary immunodeficiency, unless immune competence has been demonstrated.\n- Active untreated tuberculosis.\n- Pregnancy or planning pregnancy within one month.\n- Yellow fever or varicella vaccine within the previous 4 weeks: defer. Never give yellow fever vaccine and MMR on the same day.\n- Acute febrile illness (vaccination should be postponed)."),
            ("replace_contains", "do not improve in 3",
             "Attend for the second dose on the date given. A mild fever, rash or malaise 6 to 11 days after the dose is common and settles on its own; parotid swelling can occur in the third week. Seek medical advice for a fever that does not settle within 48 hours, a severe or persistent injection site reaction, easy bruising or bleeding, or any sign of an allergic reaction; call 999 for difficulty breathing, swelling of the face or throat, or collapse. Avoid pregnancy for one month after each dose."),
            ("replace", "Can be given from 6 months in high-risk situations (e.g. outbreaks or travel to endemic areas), but this dose does not count toward the routine schedule.",
             "Can be given from 6 months in high-risk situations (e.g. outbreaks or travel to endemic areas), but this dose does not count toward the routine schedule. It is not available under this PGD, which starts at 12 months."),
            ("replace", "Ensure a 4-week interval between doses.",
             "Ensure an interval of at least 4 weeks between doses, or at least 3 months where both doses are given under 18 months of age."),
        ],
        "changes": [
            "The cover strapline no longer names the product as 'MMRVaxPRO 5mg', a strength that does not exist; the name of medicine rows in both arms now give the form and the 0.5 mL dose.",
            "The exclusion criteria in both arms now state explicitly that egg allergy, including previous anaphylaxis to egg, is not a contraindication and not an exclusion, so that 'any other component' cannot be read as egg protein.",
            "The follow-up advice rows, which carried the treatment template about 3 to 4 weeks, now give MMR follow-up advice.",
            "The guidance summary now says that the 6 month outbreak dose is not available under this PGD, and its catch-up interval carries the 3 month rule for children under 18 months that the dose row already has.",
        ],
    },
    "pneumococcal": {
        "edits": [
            ("insert_after_contains", "Summary of the governing guidance for pneumococcal vaccination", [
                "Note: this summary describes the national programme, which uses Prevenar 20 (PCV20) from July 2026 and previously PCV15 or PCV13, and includes the infant schedule. The products authorised under this PGD are Prevenar 13 and Pneumovax 23 only, for individuals aged 2 years and over; the infant schedule is outside this PGD.",
            ]),
            ("replace_contains", "PPV23 or PCV20 received within the last 5 years, unless",
             "- Known hypersensitivity to Pneumovax 23 or any of its components.\n- Previous severe allergic reaction to any pneumococcal vaccine.\n- PPV23 or PCV20 received within the last 5 years. Revaccination with Pneumovax 23 is authorised only for asplenia, splenic dysfunction or chronic kidney disease, and only where at least 5 years have elapsed since the previous dose; it is not recommended for any other group.\n- Acute illness with fever (postpone until recovered)."),
            ("replace_contains", "- Record batch number and site of administration.",
             "- Use with caution in individuals with bleeding disorders.\n- Record batch number, expiry date and site of administration.\n- Monitor for anaphylaxis for 15 minutes after administration.\n- Inform patient of possible side effects and when to seek help."),
            ("replace_contains", "- Record batch number and expiry date in the patient record.",
             "- Observe the patient for 15 minutes post-vaccination.\n- Use with caution in patients with bleeding disorders.\n- Record batch number, expiry date and site of administration in the patient record.\n- Advise on expected side effects and when to seek medical advice."),
            ("replace", "As per national immunisation schedule, including primary and booster doses.",
             "A single dose under this PGD. Infant primary and booster doses are not given under this PGD."),
            ("replace_contains", "do not improve in 3", VACCINE_FOLLOW_UP + " Where a Pneumovax 23 dose is due after Prevenar 13, attend for it on the date given (at least 8 weeks later)."),
        ],
        "changes": [
            "The guidance summary now carries a note that it describes the national programme (Prevenar 20 from July 2026, and the infant schedule) while this PGD authorises Prevenar 13 and Pneumovax 23 only, from 2 years of age.",
            "The Pneumovax 23 exclusion for a dose within the last 5 years no longer carries the circular 'unless 5 years have elapsed' exception; revaccination is stated as the dose row has it, for asplenia, splenic dysfunction or chronic kidney disease only and only after 5 years.",
            "Both cautions rows now ask for the batch number, expiry date and site; previously one arm asked for batch and expiry and the other for batch and site.",
            "The Prevenar 13 maximum treatment period row now says a single dose under this PGD instead of 'including primary and booster doses', which the inclusion criteria exclude.",
            "The follow-up advice rows, which carried the treatment template about 3 to 4 weeks, now give vaccination follow-up advice.",
        ],
    },
}

DECISIONS = [
    ("anti-malarials",
     "Atovaquone/proguanil weight bands: the PGD uses 11 to 20 / 21 to 30 / 31 to 40 / over 40 kg (gaps at fractional weights, 40.0 kg paediatric) while UKMEAG Table 5 uses 10 to 19.9 / 20 to 29.9 / 30 to 39.9 / 40 kg and over; and mefloquine bands (PGD 21 to 30 kg half, 31 to 45 three quarters, over 45 one) differ from UKMEAG (16 to 24.9 half, 25 to 44.9 three quarters, 45 and over one). Already in the review register.",
     "Options: (a) keep the PGD bands as written; (b) rewrite both dose tables to the UKMEAG bands with decimal boundaries (x to y.9 kg) and adult tablet from 40 kg.",
     "Recommendation: (b), so that a 20.5 kg or 40.0 kg patient has a defined band and the document matches the guidance it summarises; the tool would then follow the same bands."),
    ("travellers-diarrhoea",
     "'High fever' in the exclusion criteria is not defined; the tool uses over 38.5 C.",
     "Options: (a) leave undefined; (b) define as 38 C or above (the sepsis threshold used across the GRH estate); (c) 38.5 C or above (the tool's current figure).",
     "Recommendation: (b), 38 C or above, with the tool aligned to it."),
    ("tetanus",
     "Adequate priming for the immunoglobulin rule: the edit above aligns the 'Five documented doses' block to the 3 dose definition (UKHSA Table 4) used by the cover, inclusion criteria, dose row and Appendix 1, replacing 'fewer than 5'. Chris to confirm.",
     "Options: (a) confirm 3 or more primary doses as adequate priming throughout (UKHSA Table 4); (b) revert to 'fewer than 5 documented doses' for the immunoglobulin rule, which would send a 3 or 4 dose patient with a tetanus-prone wound for immunoglobulin.",
     "Recommendation: (a); it is the UKHSA definition and the rest of the document already uses it."),
    ("travel-core",
     "Dukoral: 'severe immunocompromise' is an exclusion and 'immunocompromised patients' a caution with no boundary between them.",
     "Options: (a) define severe immunocompromise (for example current chemotherapy, within 6 months of transplant, high-dose systemic corticosteroids) as the exclusion and other immunosuppression as the caution; (b) remove the exclusion, since the vaccine is inactivated, and keep the caution only; (c) leave as is.",
     "Recommendation: (a), with the definition borrowed from the dengue PGD's exclusion wording so the estate uses one definition."),
    ("travel-core",
     "Structure: the document still has three Agreement to practise pages and three adoption blocks (one per vaccine) despite the version 004 note that one signed authorisation page replaces the earlier blocks.",
     "Options: (a) remove the second and third agreement pages and adoption blocks in the next reissue (a structural change beyond paragraph edits); (b) leave.",
     "Recommendation: (a), done by the generator rather than by anchored edits."),
    ("hep-ab-travel",
     "Consent under 16: the document has no Gillick provision (the version 002 record says the consent block was deliberately not added). The edit above defines the child as under 16 with parental responsibility consent only.",
     "Options: (a) keep parental responsibility consent only for under 16s; (b) add the estate's standard consent in children block (parental responsibility or Gillick competence, with the basis recorded), as the junior travel and rabies PGDs carry.",
     "Recommendation: (b), for consistency with the rest of the estate; the tool would then offer Gillick from 12 to 15 as it does elsewhere."),
    ("meningitis-acwy-travel",
     "Repeat MenACWY within 5 years: the edit above lists it as an exclusion (the existing reading). Is clinical discretion wanted for an at-risk individual (asplenia, complement disorder) whose specialist advises an earlier booster?",
     "Options: (a) exclusion, refer to the specialist or GP (as edited); (b) permit a repeat within 5 years on documented specialist advice.",
     "Recommendation: (a); JCVI has not set an interval for at-risk groups and the document already says not to invent one."),
    ("meningitis-acwy-travel",
     "The separate MenACWY certificate page in the tool (src/app/for-pharmacies/epgd/certificate/menacwy/page.tsx) prints 'valid for travel purposes for at least three years' while the PGD says a conjugate vaccine certificate is accepted for 5 years.",
     "Options: (a) change the certificate page to 5 years for a conjugate vaccine; (b) leave.",
     "Recommendation: (a), a tool change outside this document."),
    ("meningitis-b",
     "Bexsero at 12 months to under 2 years: the schedule covers only children 'who had fewer than 2 doses in the first year' (2 further doses) and gives nothing for a child in that band who completed two infant doses but missed the 12 month booster, and does not distinguish no doses from one dose. The Bexsero SmPC gives unvaccinated 12 to 23 month olds two doses at least 2 months apart with a booster 12 to 23 months later.",
     "Options: (a) rewrite the 12 to 23 month row to the SmPC: unvaccinated, 2 doses at least 2 months apart plus a booster 12 to 23 months after; one infant dose, complete to 2 doses then booster; two infant doses, single booster; (b) refer every child in that band to the GP.",
     "Recommendation: (a), taken from the SmPC table, with the tool's dosesInFirstYear field driving it."),
    ("pneumococcal",
     "The guidance summary still describes PCV15 / Prevenar 20 and the infant 12 week / 1 year schedule while the PGD arms are Prevenar 13 and Pneumovax 23 (on the review register since version 003).",
     "Options: (a) rewrite the summary against the July 2026 Green Book chapter 25 and add a Prevenar 20 arm for adults in risk groups if the service wants to stock it; (b) rewrite the summary only; (c) leave with the note added above.",
     "Recommendation: (b) now, and (a) if Prevenar 20 is to be offered; both are clinical rewrites beyond a wording fix."),
]
