const {build,Packer,fs}=require('./gen.js');

const d={
 banner:'ISSUED, VALID FROM 8 SEPTEMBER 2026',
 title:'Human Papillomavirus (HPV) Vaccination',
 strap:'Patient Group Direction, version 002, issued 8 September 2026. Gardasil 9, intramuscular, from 9 years of age, all sexes.',

 intro:[
  {h:'Read this first: three things version 001 got wrong'},
  {bullet:'THIS PGD COVERS ALL SEXES. HPV vaccination is for boys and men as much as for girls and women. The GBMSM cohort, which national policy singles out for protection up to 45 years of age, is male by definition. Any suggestion that this is a service for females only is wrong.',b:true},
  {bullet:'YEAST ALLERGY IS NOT A CONTRAINDICATION. Green Book chapter 18a states this in terms: Gardasil 9 is grown in yeast cells but the finished vaccine contains no yeast as an ingredient, at most trace protein below 0.007 micrograms. Version 001 listed yeast protein as a contraindication and the consultation tool refused to vaccinate anyone who reported a yeast allergy. Both were wrong and both are corrected.',b:true},
  {bullet:'PREGNANCY: DO NOT ASK ABOUT PERIODS AND DO NOT PREGNANCY TEST. Green Book chapter 18a states that routine questioning about last menstrual period and pregnancy testing is not required before offering HPV vaccine. Vaccination is postponed in a woman known to be pregnant because the SPC says the data are insufficient, not because harm has been shown. If a patient turns out to have been pregnant when vaccinated, that is not a cause for alarm and termination must not be recommended.',b:true},

  {h:'The schedule depends on age and immune status, and most of it is off-label'},
  {bullet:'UNDER 25 at the time of vaccination: ONE dose. That is the whole course. Do not book further doses.',b:true},
  {bullet:'25 AND OVER: TWO doses, the second 6 to 24 months after the first. The minimum interval for Gardasil 9 is 5 months.',b:true},
  {bullet:'IMMUNOSUPPRESSED OR KNOWN HIV POSITIVE, any age: THREE doses at 0, 1, and 4 to 6 months, ideally completed within 12 months.',b:true},
  {bullet:'THE ONE DOSE SCHEDULE AND THE TWO DOSE SCHEDULE ARE OFF-LABEL. The Gardasil 9 SPC contains no one dose schedule at all, and for anyone aged 15 or over at first injection it specifies three doses. The UK one and two dose schedules come from JCVI, not from the product licence. Consent to off-label use must be obtained and recorded. See the row below.',b:true},
  {bullet:'You must therefore ask about immunosuppression and HIV status before deciding the schedule. Version 001 never asked, and the consultation tool recommended three doses to everybody regardless of age.',b:true},
  {bullet:'A person who had one dose before their 25th birthday needs no further doses, whatever their age now.',b:true},
  {bullet:'Observe every patient for 15 minutes after vaccination, seated.',b:true},

  {h:'On charging for doses the patient does not need'},
  'This matters commercially as well as clinically. Under the schedule that version 001 and the consultation tool applied, a healthy 19 year old was told to return twice more and would have been charged for two doses that national policy says are unnecessary. Getting the schedule right is not only a safety point. Where a patient has already been given and charged for surplus doses under the old schedule, that is a matter for the pharmacy to put right with them directly.',
 ],

 arms:[{
  title:'Gardasil 9 for vaccination against human papillomavirus',
  subtitle:'Patient Group Direction for the administration of Gardasil 9 suspension for injection by the intramuscular route, for the prevention of HPV-related disease, in individuals of any sex aged 9 years and over.',
  training:[
   'Pharmacist registered and practising with the GPhC.',
   'Pharmacy technician registered and practising with the GPhC.',
   'All users must be trained to the National Minimum Standards and Core Curriculum for Immunisation Training, and be competent in intramuscular vaccination technique.',
   'All users must be competent in the recognition and immediate management of anaphylaxis, and hold current basic life support training.',
   'All users must be competent in assessing consent in children and young people, including parental responsibility and Gillick competence. This PGD starts at 9 years of age and the largest single cohort is 12 to 13 year olds, so children are squarely in scope.',
   'All users must be able to select the correct schedule from age and immune status, and must understand that the one dose and two dose schedules are off-label and require documented consent.',
   'All users must be able to manage a request from a male patient, including a GBMSM patient, without embarrassment or assumption, and must understand that this vaccine is not a female-only product.',
   'All users must be competent in vaccine handling and cold chain management, including the action to take on a cold chain excursion.',
   'All users must be familiar with the current SPC for Gardasil 9, Green Book chapter 18a, and Green Book chapter 8 on the management of anaphylaxis and the distinction between a faint, a panic attack and anaphylaxis.',
   'All users must previously have supplied or administered medicines under a PGD, must work in compliance with the SOPs of their own employer, must hold appropriate indemnity, and must practise only within the bounds of their own competence.',
  ],
  pgd:[
   ['Indication','Active immunisation of individuals from 9 years of age against premalignant lesions and cancers of the cervix, vulva, vagina and anus caused by vaccine HPV types, and against genital warts caused by HPV types 6 and 11. Gardasil 9 protects against HPV types 6, 11, 16, 18, 31, 33, 45, 52 and 58. It is prophylactic only: it has no effect on an established infection or on existing disease, and it is not a treatment.'],

   ['Inclusion criteria',[
     {bullet:'Aged 9 years and over. There is no upper age limit in the marketing authorisation. Individuals aged 9 to 11 are licensed but fall outside the national programme, so a private supply is the only route available to them.'},
     {bullet:'ANY SEX. Male, female, transgender and non-binary individuals are all in scope. The GBMSM cohort is specifically recognised in national policy up to and including 45 years of age.',b:true},
     {bullet:'Requesting vaccination privately, and made aware that they may be entitled to receive the vaccine free of charge from an NHS service. NHS eligibility is set out in the appendix. Where the patient is NHS-eligible, tell them so and record that you did.',b:true},
     {bullet:'Immune status established, so that the correct schedule can be selected. Ask directly whether the individual is immunosuppressed or known to be living with HIV.',b:true},
     {bullet:'Valid informed consent obtained. Where the individual is under 16, from a person with parental responsibility, or from the young person where assessed as Gillick competent, with the basis of that assessment recorded.',b:true},
     {bullet:'Consent to off-label use obtained and recorded where the one dose or the two dose schedule is being used. See the row below.',b:true},
     {bullet:'No exclusion criterion present.'},
   ]],

   ['The UK schedules are off-label: what to say and record',[
     {text:'The Gardasil 9 SPC provides only two schedules: a two dose 0 and 6 to 12 month course for individuals aged 9 to and including 14 at first injection, and a three dose 0, 2 and 6 month course for individuals aged 15 and over at first injection. It contains no one dose schedule for anybody.',b:true},
     {text:'It follows that:',b:true},
     {bullet:'The single dose given to an immunocompetent individual under 25 is off-label in every case.'},
     {bullet:'The two dose course given from 25 years of age is off-label, because the SPC requires three doses from 15 years.'},
     {bullet:'The three dose 0, 1 and 4 to 6 month course sits within the SPC minimum intervals and is not off-label on that ground.'},
     {text:'Green Book chapter 18a recommends these schedules but does not itself flag their licensing status. This PGD states it plainly so that nobody administers an off-label schedule believing it to be licensed.',b:true},
     {text:'Where an off-label schedule is used, tell the patient all of the following and record that you did:',b:true},
     {bullet:'That the number of doses being given follows current UK national recommendations from the Joint Committee on Vaccination and Immunisation.'},
     {bullet:'That this differs from the manufacturer’s licence, which specifies more doses.'},
     {bullet:'That the recommendation reflects evidence published since the licence was granted showing that fewer doses give comparable protection in this age group.'},
     {bullet:'That they may choose the licensed schedule instead if they prefer, and what that would involve.'},
     {text:'Record the consent as given for off-label use, naming the schedule. A general consent to vaccination is not sufficient.',b:true},
   ]],

   ['Exclusion criteria',[
     {text:'Refer, do not vaccinate, where any of the following applies.',b:true},
     {bullet:'Confirmed anaphylactic reaction to a previous dose of any HPV vaccine.'},
     {bullet:'Confirmed anaphylactic reaction to any component of Gardasil 9, or hypersensitivity following previous administration of Gardasil 9 or Gardasil / Silgard.'},
     {bullet:'Acute severe febrile illness or acute systemic upset. Postpone until fully recovered. A minor illness without fever is not a reason to defer.'},
     {bullet:'Known to be pregnant. Postpone until after the pregnancy. Do not question about last menstrual period and do not pregnancy test, in line with Green Book chapter 18a.',b:true},
     {bullet:'Has already completed a full course of HPV vaccine appropriate to their age and immune status, including anybody who received a single dose before their 25th birthday.',b:true},
     {bullet:'Under 16 and valid consent cannot be obtained from a person with parental responsibility, and the young person is not assessed as Gillick competent.',b:true},
     {bullet:'Consent to off-label use not obtained, where an off-label schedule would be used.'},
     {text:'YEAST ALLERGY IS NOT AN EXCLUSION. Vaccinate. Green Book chapter 18a is explicit that yeast allergy does not contraindicate HPV vaccine.',b:true},
   ]],

   ['Cautions',[
     {text:'Immunosuppression and HIV. Not a reason to withhold the vaccine, but it changes the schedule to three doses. Eligible GBMSM known to be HIV positive should be offered the vaccine regardless of CD4 count, antiretroviral therapy or viral load. The response may still be suboptimal, and in transplant recipients additional doses may be considered after treatment finishes; that is a specialist decision, not one for this PGD.',b:true},
     {text:'Bleeding disorders, thrombocytopenia and anticoagulation. Intramuscular vaccination is generally acceptable. Use a 23 gauge or finer needle and apply firm pressure without rubbing for at least two minutes. For a patient on treatment for haemophilia, schedule shortly after that treatment. A patient on stable warfarin who is up to date with INR testing and whose latest INR is below the top of their therapeutic range may be vaccinated intramuscularly. If in any doubt, contact the clinician responsible for the anticoagulation.'},
     {text:'Breastfeeding. Gardasil 9 can be used during breastfeeding. Not a reason to defer.'},
     {text:'Syncope. Fainting, sometimes with tonic-clonic movements on recovery, can occur before or after any injection and is commonest in adolescents. It is a response to the needle, not to the vaccine. Vaccinate seated and have procedures in place to prevent injury from a faint.',b:true},
     {text:'This vaccine will not protect against every HPV type and does not clear an existing infection. It is not a substitute for cervical screening, and it is not a substitute for barrier protection against sexually transmitted infection.'},
     {text:'Complete a course with Gardasil 9 wherever possible. Where an individual started a course overseas with a different HPV vaccine, evidence supports interchangeability and a mixed schedule may be completed.'},
     {text:'Immunoglobulin or blood products within the previous three months. Not studied. Not a contraindication, but record it.'},
   ]],

   ['Anaphylaxis and observation',[
     {text:'Adrenaline (epinephrine) 1 in 1,000 injection must be immediately available in the room whenever a vaccine is administered under this PGD, in date, together with a written anaphylaxis protocol consistent with current Resuscitation Council UK guidance, and a telephone.',b:true},
     {text:'All staff administering vaccines must be trained in the recognition and immediate management of anaphylaxis and must hold current basic life support training.'},
     {text:'OBSERVE EVERY PATIENT FOR 15 MINUTES AFTER VACCINATION, SEATED. The Gardasil 9 SPC specifies approximately 15 minutes because of syncope. Version 001 mentioned 15 minutes only in passing among the cautions and stated no requirement for adrenaline to be available at all.',b:true},
     {text:'Be able to distinguish a faint and a panic attack from anaphylaxis. Green Book chapter 8 sets out the clinical features of each. A faint after an injection in an adolescent is common; anaphylaxis is very rare.'},
   ]],

   ['Actions if the patient is excluded or declines',[
     {bullet:'Discuss the reason with the patient and make sure they understand it.'},
     {bullet:'Where the patient is NHS-eligible, direct them to the NHS route rather than simply declining. Adolescents are vaccinated in school; GBMSM up to 45 are vaccinated at sexual health and HIV services.',b:true},
     {bullet:'Where vaccination is postponed for pregnancy or acute illness, agree when they should come back and say so clearly. A postponement is not a refusal.'},
     {bullet:'Where the exclusion is a previous anaphylactic reaction, refer to the GP or an allergy service; do not simply turn the patient away.'},
     {bullet:'Document the reason for exclusion, the advice given and the decision reached. Inform or refer to the GP as appropriate.'},
   ]],

   ['Yellow Card reporting','Report suspected adverse reactions via https://yellowcard.mhra.gov.uk and inform the GP as appropriate. Anaphylaxis after any vaccine should be reported even where the diagnosis is uncertain.'],

   ['Records to be kept',[
     {bullet:'That valid informed consent was given, and from whom. Where the individual is under 16, the name and relationship of the person with parental responsibility, or the basis of the Gillick assessment.',b:true},
     {bullet:'Where an off-label schedule was used, that consent to off-label use was given, naming the schedule.',b:true},
     {bullet:'Patient name, address, date of birth, and the GP with whom they are registered.'},
     {bullet:'Immune status as established at the consultation, because it determines the schedule.',b:true},
     {bullet:'Vaccine name and batch number, and expiry date. The SPC requires the name and batch of any biological product to be recorded for traceability.',b:true},
     {bullet:'Which schedule was selected and the reason, being the patient’s age at first dose and their immune status.',b:true},
     {bullet:'Dose number in the course, and the date the next dose is due, or that no further dose is required.',b:true},
     {bullet:'Date of administration, dose volume, route and anatomical site. Where another vaccine was given at the same visit, the site of each.'},
     {bullet:'That the patient was told whether they are eligible for NHS vaccination.',b:true},
     {bullet:'Name and registration number of the healthcare professional administering.'},
     {bullet:'That the 15 minute observation period was completed.',b:true},
     {bullet:'Advice given, including advice given if the patient is excluded or declines.'},
     {bullet:'Details of any adverse drug reactions and the actions taken.'},
     {bullet:'That the vaccine was administered under this PGD.'},
     {text:'Records signed, dated, legible and contemporaneous. Adults 18 and over: 8 years. Under 18s: until the 25th birthday, or the 26th where the patient was 17 when the course finished. Give the patient a written record of the dose and, where applicable, the date the next one is due.'},
   ]],
  ],
  med:[
   ['Name, form and strength',[
     {bullet:'GARDASIL 9 suspension for injection, or Gardasil 9 suspension for injection in a pre-filled syringe. Merck Sharp and Dohme (UK) Limited. PLGB 53095/0023.'},
     {bullet:'0.5 mL per dose, containing L1 protein virus-like particles of HPV types 6, 11, 16, 18, 31, 33, 45, 52 and 58, adsorbed on amorphous aluminium hydroxyphosphate sulfate adjuvant.'},
     {bullet:'Produced in Saccharomyces cerevisiae. The finished vaccine contains no yeast as an excipient. Yeast allergy is not a contraindication.',b:true},
     {bullet:'Excipients: sodium chloride, histidine, polysorbate 80, borax, water for injections. Essentially sodium-free. Thiomersal free.'},
     {bullet:'Gardasil 9 is the only HPV vaccine supplied for the UK national programme.'},
   ]],
   ['Legal category','POM.'],
   ['Dose and frequency',[
     {text:'SELECT THE SCHEDULE FROM AGE AT FIRST DOSE AND IMMUNE STATUS.',b:true},
     {bullet:'IMMUNOCOMPETENT, UNDER 25 at vaccination: ONE dose of 0.5 mL. Course complete. Off-label.',b:true},
     {bullet:'IMMUNOCOMPETENT, 25 AND OVER: TWO doses of 0.5 mL, the second 6 to 24 months after the first. Minimum interval for Gardasil 9 is 5 months. Any gap between 6 and 24 months is clinically acceptable. Off-label.',b:true},
     {bullet:'IMMUNOSUPPRESSED OR KNOWN HIV POSITIVE, any age: THREE doses of 0.5 mL at 0, 1, and 4 to 6 months. All three ideally within 12 months.',b:true},
     {bullet:'A person who received a single dose before their 25th birthday requires no further doses.'},
     {bullet:'Interrupted course: resume, do not repeat, even where more than 24 months have elapsed. Allow the appropriate interval between the remaining doses.'},
     {bullet:'Dose given too early in error: discount it, and repeat once the correct interval has elapsed and at least 4 weeks after the dose given early.',b:true},
     {bullet:'On the three dose course, where the second dose was late and the patient is unlikely to return after three months, the third dose may be given at least one month after the second.'},
     {bullet:'The need for a booster has not been established. Do not offer one.'},
   ]],
   ['Quantity to be administered','One 0.5 mL dose per patient per attendance, in accordance with the schedule above. This PGD does not permit supply of vaccine to the patient for administration elsewhere.'],
   ['Route and method of administration','Intramuscular. Preferred site the deltoid area of the upper arm, or the higher anterolateral thigh. Never intravascularly, subcutaneously or intradermally, and never mixed in a syringe with another vaccine. Shake well before use: the suspension is a clear liquid with a white precipitate before agitation and a white cloudy liquid after. Inspect for particles and discolouration and discard if either is present. Administer as soon as possible after removal from the refrigerator. Gardasil 9 may be given at the same visit as other vaccines including Td/IPV, MMR, influenza, MenACWY and hepatitis B, at a separate site, preferably a different limb, or at least 2.5 cm apart, recording the site of each.'],
   ['Storage and cold chain',[
     {text:'Store at +2C to +8C in the original outer carton to protect from light. Do not freeze. Discard if frozen.'},
     {text:'COLD CHAIN EXCURSION: the SPC states that the vaccine components are stable for 96 hours at 8C to 40C, or for 72 hours at 0C to 2C, after which the vaccine must be used or discarded. That figure guides a temporary excursion only. Any stock exposed outside +2C to +8C must be quarantined and risk assessed in accordance with UKHSA Vaccine Incident Guidance before further use. Do not administer excursion stock until that assessment is complete. Version 001 carried no cold chain excursion procedure at all.',b:true},
   ]],
   ['Disposal','Dispose of used syringes, needles, vials and any unused vaccine in a UN-approved puncture-resistant sharps container in accordance with local authority requirements and HTM 07-01, Safe management of healthcare waste. Version 001 carried no disposal provision.'],
   ['Adverse effects','Very common: injection site pain, swelling and erythema; headache. Common: pyrexia, fatigue, dizziness, nausea, injection site pruritus and bruising. Uncommon: lymphadenopathy, syncope sometimes with tonic-clonic movements, vomiting, urticaria, arthralgia, myalgia, asthenia, chills, malaise, injection site nodule. Rare: hypersensitivity. Not known: anaphylactic reactions. Reported after the related quadrivalent vaccine: injection site cellulitis, idiopathic thrombocytopenic purpura, anaphylactoid reactions, bronchospasm, acute disseminated encephalomyelitis and Guillain-Barre syndrome, with causality not established. Consult the current SPC.'],
  ],
  pat:[
   ['Written information','Supply the patient information leaflet provided with the vaccine, and a written record showing the vaccine name, batch number, date, site, dose number and either the date the next dose is due or a clear statement that the course is complete.'],
   ['Counselling',[
     {bullet:'If you are under 25 and not immunosuppressed, one dose is the whole course. You do not need to come back. This is current national policy and it is not us cutting corners.',b:true},
     {bullet:'This vaccine protects against the HPV types that cause most cervical and other anogenital cancers, most HPV-related throat cancers, and most genital warts.'},
     {bullet:'It works best before you are exposed to the virus, but it is still worth having later.'},
     {bullet:'It cannot treat an infection you already have, and it will not clear existing warts or abnormal cells.',b:true},
     {bullet:'Keep going to cervical screening when you are invited. The vaccine does not cover every HPV type and screening still matters.',b:true},
     {bullet:'Keep using condoms. This vaccine protects against HPV, not against other sexually transmitted infections or pregnancy.'},
     {bullet:'A sore arm, headache, mild fever or tiredness for a day or two is common and settles by itself.'},
     {bullet:'Some people feel faint around injections. That is why we ask you to stay seated with us for 15 minutes.'},
     {bullet:'If you are eligible for this free on the NHS, we will tell you, and you are free to go that route instead.',b:true},
   ]],
   ['Follow-up','Where a further dose is due, book it at this appointment and give the date in writing. Seek medical advice for any severe or persistent reaction, for any rash or swelling that spreads, or for any breathing difficulty. For routine queries contact the pharmacy.'],
  ],
 }],

 appendix:[
  {h:'Appendix 1: NHS eligibility, for the conversation you must have'},
  'Every patient must be told whether they could get this vaccine free on the NHS. This appendix is the reference for that conversation. It is not a list of who may be vaccinated under this PGD: this PGD covers anyone aged 9 and over who meets the inclusion criteria, NHS-eligible or not.',
  {bullet:'All adolescents, of any sex, from 11 years of age, offered in school year 8 in England and Wales, S1 in Scotland and year 9 in Northern Ireland.'},
  {bullet:'Individuals in those eligible cohorts remain eligible until their 25th birthday. For England the cohorts are females born after 1 September 1991 and males born after 1 September 2006. Cut-offs differ in Scotland, Wales and Northern Ireland.'},
  {bullet:'Those cohorts include people who have moved to the UK from overseas, are registered with a GP practice, are under 25, and were not offered HPV vaccination in their country of origin.'},
  {bullet:'All GBMSM up to and including 45 years of age attending specialist sexual health services or HIV services, regardless of risk, behaviour or disease status.'},
  {bullet:'Anyone who started but did not complete the GBMSM course before reaching 46 should be allowed to complete it.'},
  {bullet:'Some transgender individuals, sex workers and people living with HIV attending those services, where their risk is judged equivalent to that of eligible GBMSM.'},
  {bullet:'Children aged 9 to 11 are licensed for the vaccine but are NOT covered by the national programme. A private supply under this PGD is their only route.',b:true},

  {h:'Appendix 2: Key references'},
  {bullet:'Immunisation Against Infectious Disease (the Green Book), chapter 18a, Human papillomavirus, June 2023, incorporating the move to a one dose schedule from 1 September 2023.'},
  {bullet:'Immunisation Against Infectious Disease (the Green Book), chapter 8, Vaccine safety and the management of adverse events, for the management of anaphylaxis and the distinction between a faint, a panic attack and anaphylaxis.'},
  {bullet:'Summary of Product Characteristics for Gardasil 9, Merck Sharp and Dohme (UK) Limited, PLGB 53095/0023, text last revised 13 September 2024.'},
  {bullet:'JCVI advice on the HPV immunisation programme, and the bipartite letter of 20 June 2023 on the change to a one dose schedule from September 2023.'},
  {bullet:'UKHSA Vaccine Incident Guidance, for cold chain excursions.'},
  {bullet:'Health Technical Memorandum 07-01, Safe management of healthcare waste.'},
  {bullet:'NICE Medicines Practice Guideline 2 (MPG2): Patient Group Directions, https://www.nice.org.uk/guidance/mpg2'},
 ],

 version:'v003',
 supersedes:'Version 002, 8 September 2026',
 validFrom:'9 September 2026',
 expiry:'31 July 2027',
 sigDate:'9 September 2026',
 chDate:'9 September 2026',
 changes:[
  'The practitioner Agreement to practise page, the premises block and the practitioner signature table are restored, together with the standard governance requirements: SPC and BNF familiarity, MHRA safety alerts, CPD and appraisal, indemnity, and capacity and consent. Every version 001 document carried them; no document produced by the current generator did, through one omission in one function that affected 15 live documents. Raised as blocking by an adopting pharmacy. This version changes no clinical content.',
  'The document and the consultation tool are corrected to cover all sexes. Version 001 described the national cohorts correctly, including GBMSM up to 45 years of age, but the consultation tool required a "female confirmed" tick before it would proceed and would not produce a dose recommendation for a male patient at all. A PGD that names the GBMSM cohort while its tool refuses to vaccinate men is not a service; the tool has been rebuilt alongside this version.',
  'Yeast allergy removed as a contraindication. Green Book chapter 18a states that yeast allergy does not contraindicate HPV vaccine because the finished product contains no yeast as an ingredient. Version 001 listed yeast protein among its contraindications and the tool applied a hard stop to it, so patients were being refused a vaccine they could safely have.',
  'The schedule is now selected from age and immune status, and is stated once instead of twice. Version 001 gave the JCVI schedules under "dose and frequency" and the SPC schedules under "maximum or minimum treatment period", so the document set out two incompatible courses and never said which to follow. The tool, meanwhile, recommended three doses at 0, 2 and 6 months to every patient regardless of age, which meant an immunocompetent person under 25 was being asked to return, and to pay, for two doses that national policy says they do not need.',
  'The one dose and two dose schedules are identified as off-label, with a stated consent script and a requirement to record consent to off-label use naming the schedule. The Gardasil 9 SPC contains no one dose schedule and requires three doses from 15 years of age; the UK schedules come from JCVI. Green Book chapter 18a recommends them without flagging their licensing status, so a pharmacist relying on the chapter alone would not know.',
  'Immune status must now be established before the schedule is chosen, and recorded. Version 001 gave a three dose schedule for immunosuppressed patients but never required anyone to ask.',
  'Pregnancy handling corrected. Green Book chapter 18a states that routine questioning about last menstrual period and pregnancy testing is not required, and that termination must not be recommended after inadvertent immunisation. Version 001 excluded pregnancy without either statement, and the tool told the pharmacist to "counsel on avoiding conception during the course", which has no basis in the guidance and would alarm a patient for no reason.',
  'A requirement for adrenaline 1 in 1,000 to be immediately available in the room, with a written anaphylaxis protocol and a telephone, and for staff to be trained in anaphylaxis management and hold current basic life support. Version 001 carried the SPC boilerplate that treatment should be "readily available" and no requirement of any kind.',
  'A 15 minute observation period after every vaccination, seated, stated as a requirement rather than mentioned among the cautions.',
  'A cold chain excursion procedure added, using the concrete SPC stability figures of 96 hours at 8C to 40C or 72 hours at 0C to 2C, together with quarantine and risk assessment under UKHSA Vaccine Incident Guidance. Version 001 had none.',
  'A sharps disposal provision added, referencing HTM 07-01. Version 001 had none.',
  'Consent in children and young people added: parental responsibility, or Gillick competence with the basis recorded. This PGD starts at 9 years of age and its largest cohort is 12 to 13 year olds, yet version 001 said only "informed consent obtained or parental/guardian consent as appropriate". Found by an estate-wide sweep of every vaccination PGD on 8 September 2026, which flagged the same gap in nine documents.',
  'Bleeding disorder guidance expanded from a bare caution to the Green Book chapter 18a practical instruction: 23 gauge or finer needle, firm pressure without rubbing for at least two minutes, and the position on haemophilia treatment and stable warfarin.',
  'Records must now carry immune status, the schedule selected and why, the batch number, the dose number and next dose date or a statement that the course is complete, the site of each vaccine where more than one was given, that the observation period was completed, and that the patient was told whether they are NHS-eligible.',
  'The requirement to tell every patient whether they could have the vaccine free on the NHS is moved from a passing clause in the inclusion criteria into an explicit recorded step, with the eligibility cohorts set out in an appendix.',
 ],
 prior:[
  ['002, 8 September 2026','All sexes covered and the tool rebuilt; yeast allergy removed as a contraindication; schedule selected from age and immune status; the one dose and two dose schedules identified as off-label.'],
  ['001, 16 February 2026','Development and issue of new PGD. Gardasil 9 from 9 years of age.'],
 ],
};

Packer.toBuffer(build(d)).then(b=>{fs.writeFileSync('hpv-v003-SIGNED.docx',b);console.log('hpv v002 docx bytes',b.length);});
