const {build,Packer,fs}=require('./gen.js');

const d={
 banner:'ISSUED, VALID FROM 8 SEPTEMBER 2026',
 title:'Plaque Psoriasis (Calcipotriol with Betamethasone)',
 strap:'Patient Group Direction, version 003, issued 8 September 2026. Calcipotriol 50 micrograms/g with betamethasone 0.5 mg/g, as ointment, gel, cream or cutaneous foam. Adults 18 and over, stable plaque psoriasis.',
 purpose:{
   for:'The supply of a combined topical treatment to an adult with a flare of stable plaque psoriasis on the trunk, limbs or scalp, by a registered pharmacist or registered pharmacy technician in a community pharmacy, without a prescription.',
   authorises:[
    'Calcipotriol 50 micrograms/g with betamethasone (as dipropionate) 0.5 mg/g, as ointment, gel, cream or cutaneous foam, once daily for up to 4 weeks, in adults aged 18 years and over.',
   ],
   notFor:[
    'The face, flexures or genital skin, where a potent steroid is not used.',
    'Generalised pustular psoriasis or erythroderma. Refer as an emergency.',
    'Psoriasis affecting more than 30% of the body surface, or needing more than 15g of product in a day. Refer.',
    'Anyone under 18.',
   ],
  },

 intro:[
  {h:'The three things this version adds'},
  {bullet:'ERYTHRODERMIC, EXFOLIATIVE AND PUSTULAR PSORIASIS ARE ABSOLUTE CONTRAINDICATIONS and were not mentioned anywhere in version 001. They are also dermatological emergencies. See Appendix 1.',b:true},
  {bullet:'REBOUND ON STOPPING. Discontinuing a potent topical steroid in psoriasis can precipitate generalised pustular psoriasis.',b:true},
  {bullet:'REPEAT SUPPLY IS NOW CAPPED. One 4 week course, then GP review.',b:true},
  {bullet:'The product and strength were already correct in version 001 and are unchanged: calcipotriol 50 micrograms/g with betamethasone 0.5 mg/g as dipropionate.'},

  {h:'This is stable plaque psoriasis only'},
  {bullet:'The licensed indication is stable plaque psoriasis vulgaris amenable to topical therapy, in adults.',b:true},
  {bullet:'There is no experience with this product in GUTTATE psoriasis. Refer.',b:true},
  {bullet:'Erythrodermic, exfoliative and pustular psoriasis are contraindicated and are emergencies. Refer the same day. See Appendix 1 for how to recognise them.',b:true},
  {bullet:'Not for the face, genitals or flexures. The skin there is very sensitive to corticosteroids and the SPC says the product should not be used on those sites.',b:true},

  {h:'The numbers'},
  {bullet:'Once daily to affected areas.'},
  {bullet:'MAXIMUM 15g IN ANY ONE DAY. This is the SPC limit and it is what protects against hypercalcaemia.',b:true},
  {bullet:'MAXIMUM 30% OF BODY SURFACE treated. Above that, refer; do not supply and advise partial use.',b:true},
  {bullet:'Up to 100g supplied per week, within the 15g daily limit.'},
  {bullet:'FOUR WEEKS, then stop and review. Continuing or restarting beyond 4 weeks requires medical review and ongoing medical supervision, which is a GP decision and not a PGD one.',b:true},
 ],

 guidelines:require('./guidelines/psoriasis.js'),

 arms:[{
  title:'Calcipotriol 50 micrograms/g with betamethasone 0.5 mg/g',
  subtitle:'Patient Group Direction for the supply of calcipotriol 50 micrograms/g with betamethasone (as dipropionate) 0.5 mg/g, as ointment, gel, cream or cutaneous foam, for stable plaque psoriasis in adults aged 18 years and over.',
  training:[
   'Pharmacist registered and practising with the GPhC.',
   'Pharmacy technician registered and practising with the GPhC.',
   'All users must be familiar with the current SPC for the formulation supplied, and with the BNF.',
   'ALL USERS MUST BE ABLE TO RECOGNISE ERYTHRODERMIC AND PUSTULAR PSORIASIS and must know that both are emergencies rather than a reason to supply a stronger cream. See Appendix 1.',
   'All users must be able to distinguish stable plaque psoriasis from guttate psoriasis, and to recognise secondary infection of a plaque.',
   'All users must be able to estimate body surface area using the patient’s palm as roughly 1%, and to apply the 30% limit.',
   'All users must understand that stopping a potent topical steroid abruptly can precipitate generalised pustular psoriasis, and must be able to explain the step-down to the patient.',
   'All users must previously have supplied medicines under a PGD.',
   'All users must understand capacity and consent and be aware of the Mental Capacity Act 2005.',
   'All users must hold appropriate indemnity covering this service, must work in compliance with the SOPs of their own employer, and must practise only within the bounds of their own competence.',
  ],
  pgd:[
   ['Indication','Topical treatment of stable plaque psoriasis vulgaris amenable to topical therapy, in adults aged 18 years and over, where systemic therapy is not required and a fixed-dose combination topical treatment is appropriate.'],

   ['Inclusion criteria',[
     {bullet:'Adults aged 18 years or older.'},
     {bullet:'Stable plaque psoriasis, diagnosed or previously diagnosed, mild to moderate, amenable to topical therapy.'},
     {bullet:'Affected area 30% of body surface or less. Use the patient’s palm as roughly 1%.',b:true},
     {bullet:'Lesions on the trunk, limbs or scalp. Not the face, genitals or flexures.',b:true},
     {bullet:'No exclusion criterion present, and no red flag from Appendix 1.',b:true},
     {bullet:'Informed consent given.'},
     {bullet:'FIRST 4 WEEK COURSE, or a further course where the GP has reviewed and agreed continuation. See the repeat supply row.',b:true},
   ]],

   ['Exclusion criteria: the form of psoriasis',[
     {text:'These are SPC contraindications AND emergencies. Refer the same day, and do not supply.',b:true},
     {bullet:'ERYTHRODERMIC PSORIASIS: widespread redness affecting most of the skin, with scaling, often with shivering, feeling unwell, or being unable to keep warm. This is a medical emergency; patients can lose fluid, heat and protein and become septic.',b:true},
     {bullet:'PUSTULAR PSORIASIS: sheets or clusters of small sterile pustules on red skin, whether localised to palms and soles or generalised. Generalised pustular psoriasis is a medical emergency.',b:true},
     {bullet:'EXFOLIATIVE psoriasis, meaning widespread peeling or shedding of the skin.',b:true},
     {bullet:'GUTTATE psoriasis: multiple small drop-like lesions, often after a sore throat. There is no experience with this product in guttate psoriasis. Refer.',b:true},
     {bullet:'Unstable or rapidly worsening psoriasis of any kind.'},
     {bullet:'None of the above were mentioned anywhere in version 001.',i:true,color:'9C0006'},
   ]],

   ['Exclusion criteria: all other',[
     {text:'Refer, do not supply, where any of the following applies.',b:true},
     {bullet:'Under 18 years of age. Safety and efficacy have not been established below 18.'},
     {bullet:'Hypersensitivity to calcipotriol, to betamethasone or any corticosteroid, or to any excipient of the formulation supplied.'},
     {bullet:'KNOWN DISORDER OF CALCIUM METABOLISM. This is an SPC contraindication because of the calcipotriol content, and it was absent from version 001.',b:true},
     {bullet:'More than 30% of body surface affected, or the patient would need more than 15g in a day.',b:true},
     {bullet:'Facial, genital or flexural psoriasis. Refer; the skin at those sites is very sensitive to corticosteroids.',b:true},
     {bullet:'Viral skin lesions including herpes simplex and varicella; fungal or bacterial skin infection; parasitic skin infection; skin manifestations of tuberculosis or syphilis.',b:true},
     {bullet:'Perioral dermatitis, rosacea, acne rosacea or acne vulgaris.'},
     {bullet:'Atrophic skin, striae atrophicae, fragility of skin veins, or ichthyosis.',b:true},
     {bullet:'Ulcers or wounds in or near the area to be treated.'},
     {bullet:'Secondary infection of the plaques. Treat the infection first, under the appropriate PGD or by referral; if infection worsens, the corticosteroid must be stopped.',b:true},
     {bullet:'Currently using any other topical corticosteroid on the same area. Concurrent treatment with other steroids on the same site must be avoided.',b:true},
     {bullet:'Current phototherapy, or systemic immunosuppressive or systemic anti-psoriatic treatment.'},
     {bullet:'Pregnant, planning pregnancy, or breastfeeding.',b:true},
     {bullet:'Severe renal impairment or severe hepatic disease. Safety and efficacy have not been evaluated.'},
     {bullet:'Already had a 4 week course under this PGD without GP review since. See repeat supply.',b:true},
     {bullet:'Informed consent not given.'},
   ]],

   ['Repeat supply, and why it is capped',[
     {text:'Repeat supply with no limit on how many times is indefinite supply of a potent topical corticosteroid with no review, which is not what a PGD is for.',b:true},
     {text:'Under this version:',b:true},
     {bullet:'ONE 4 week course may be supplied under this PGD.'},
     {bullet:'A further course requires that the GP has reviewed the patient since the last course and agreed continuation. Ask, and record the answer and the date.',b:true},
     {bullet:'MAXIMUM THREE 4 WEEK COURSES IN ANY 12 MONTHS under this PGD, whatever the GP has said. Beyond that, refer.',b:true},
     {bullet:'The SPC is explicit: continuing or restarting after 4 weeks should be under medical review and regular medical supervision. A pharmacy supply is not medical supervision.',b:true},
     {text:'Psoriasis is a lifelong condition. This service treats a flare; it does not manage the disease.',b:true},
   ]],

   ['Stopping the treatment: rebound',[
     {bullet:'Stopping a potent topical corticosteroid abruptly in psoriasis can precipitate GENERALISED PUSTULAR PSORIASIS, or a rebound flare worse than the original.',b:true},
     {bullet:'The SPC records a case of a patient who used far above the maximum dose for 5 months, developed Cushing syndrome, and then developed pustular psoriasis after abruptly stopping.'},
     {text:'What to tell every patient:',b:true},
     {bullet:'Do not simply stop at 4 weeks and do nothing. Continue emollients, and see your GP as arranged.'},
     {bullet:'Seek medical advice the same day if, after stopping, the skin becomes widely red and sore, starts shedding, or develops crops of small pustules.',b:true},
     {bullet:'Do not restart the cream yourself to control a rebound. Come back or see the GP.',b:true},
   ]],

   ['Cautions',[
     {text:'Do not use under occlusive dressings. Occlusion increases systemic absorption of the corticosteroid.',b:true},
     {text:'Avoid application to large areas of damaged skin, mucous membranes or skin folds, for the same reason.'},
     {text:'Wash hands thoroughly after each application to avoid transfer to the face, mouth and eyes.',b:true},
     {text:'Do not shower or bathe immediately after application.'},
     {text:'Advise the patient to limit or avoid excessive natural or artificial sunlight during treatment. Calcipotriol may enhance the effect of UV radiation.',b:true},
     {text:'VISUAL DISTURBANCE. Blurred vision or other visual symptoms have been reported with topical as well as systemic corticosteroids. Refer to an ophthalmologist for evaluation: possible causes include cataract, glaucoma and central serous chorioretinopathy.',b:true},
     {text:'Hypercalcaemia can occur if the 15g daily maximum is exceeded. Symptoms include increased urination, constipation, muscle weakness and confusion. It resolves on stopping.',b:true},
     {text:'Diabetes: systemic absorption of a potent corticosteroid can affect glycaemic control. Advise closer monitoring during the course.'},
     {text:'The ointment contains butylhydroxytoluene (E321), which may cause contact dermatitis or irritation of the eyes and mucous membranes.'},
     {text:'Long-term use increases the risk of local effects (skin atrophy, telangiectasia, striae, folliculitis, depigmentation) and systemic effects (adrenal suppression, cataract, raised intraocular pressure). This is why the course is capped.',b:true},
   ]],

   ['Actions if the patient is excluded or declines','Explain why supply is not appropriate and what to do instead. Where the presentation is erythrodermic, pustular or exfoliative, make the urgency explicit and arrange same-day assessment rather than a routine appointment; those patients need to be seen today. Where the exclusion is extent, area or a repeat beyond the cap, explain that the issue is the limits of this service rather than the treatment being wrong for them, and refer to the GP. Advise emollients in every case, which are appropriate at any severity and need no PGD. Document the advice given and the decision reached.'],
  ],
  med:[
   ['Name, form and strength',[
     {bullet:'Calcipotriol 50 micrograms/g with betamethasone (as dipropionate) 0.5 mg/g.'},
     {bullet:'OINTMENT: for body and limb plaques. Examples: Dovobet ointment, and generic equivalents.'},
     {bullet:'GEL: licensed for scalp as well as body. Examples: Dovobet gel, and generic equivalents.'},
     {bullet:'CUTANEOUS FOAM: Enstilar.'},
     {bullet:'CREAM: Wynzora.'},
     {bullet:'CHECK THE FORMULATION IS LICENSED FOR THE SITE BEING TREATED before supplying. The strength is the same across all four; the licensed sites are not.',b:true},
     {bullet:'Xamiol gel is discontinued and must not be ordered.',b:true},
   ]],
   ['Legal category','POM. A potent (group III) corticosteroid; the label will state strong steroid.'],
   ['Dose and frequency','Apply once daily to affected areas. MAXIMUM 15g IN ANY ONE DAY. Body surface treated must not exceed 30%.'],
   ['Quantity to be supplied','Up to 100g per week, within the 15g daily maximum and appropriate to the area treated. Supply enough for the 4 week course and no more.'],
   ['Maximum treatment period','4 WEEKS. One course under this PGD. A further course only where the GP has reviewed since, and a maximum of three courses in any 12 months.'],
   ['Route and method of administration','Topical, to affected skin only. Allow the preparation to remain on the skin or scalp; do not shower or bathe immediately after applying. Wash hands thoroughly after each application. Do not use under occlusive dressings.'],
   ['Storage','Store below 25 degrees Celsius. Do not refrigerate. Keep the container tightly closed. Follow the SPC for the formulation supplied; after first opening the ointment has a 1 year shelf life.'],
   ['Drug interactions','No interaction studies have been performed. The material point is concurrent topical treatment: do not use another topical corticosteroid on the same area, and do not combine with other topical anti-psoriatic products, systemic anti-psoriatic treatment or phototherapy, for which there is limited or no experience.'],
   ['Adverse effects','Common: skin exfoliation, pruritus. Uncommon: skin atrophy, exacerbation of psoriasis, dermatitis, erythema, rash, purpura or ecchymosis, burning sensation, skin irritation, folliculitis, skin infection, application site pigmentation change and pain. Rare: PUSTULAR PSORIASIS, REBOUND EFFECT, hypercalcaemia, striae, photosensitivity, acne, dry skin, furuncle, hypersensitivity. Not known: blurred vision. Systemic corticosteroid effects including adrenal suppression, cataract and raised intraocular pressure can occur, more frequently with occlusion, large areas or long-term treatment.'],
   ['Yellow Card reporting','Report suspected adverse reactions via https://yellowcard.mhra.gov.uk and inform the GP.'],
   ['Records to be kept',[
     {bullet:'That valid informed consent was given.'},
     {bullet:'Patient name, address, date of birth, and the GP with whom they are registered.'},
     {bullet:'THE FORM OF PSORIASIS, recorded as stable plaque, and that erythrodermic, pustular, exfoliative and guttate presentations were considered and excluded.',b:true},
     {bullet:'BODY SURFACE AREA AFFECTED, as a percentage, and how it was estimated.',b:true},
     {bullet:'Sites treated, and confirmation that the face, genitals and flexures are not involved.'},
     {bullet:'Which formulation was supplied and that it is licensed for the site treated.',b:true},
     {bullet:'Name and brand of the product, quantity supplied, and the date.'},
     {bullet:'WHETHER THIS IS A FIRST COURSE OR A REPEAT. Where a repeat, the date of the GP review that agreed continuation, and the number of courses in the last 12 months.',b:true},
     {bullet:'That the rebound advice was given, in terms.',b:true},
     {bullet:'Name and registration number of the healthcare professional supplying.'},
     {bullet:'Advice given, including advice given if the patient is excluded or declines.'},
     {bullet:'Details of any adverse drug reactions and the actions taken.'},
     {bullet:'That the medicine was supplied under this PGD.'},
     {text:'Records signed, dated, legible and contemporaneous. Electronic records are acceptable. Keep for 8 years.'},
   ]],
   ['Disposal','Advise the patient to return any unused product to a pharmacy.'],
  ],
  pat:[
   ['Written information','Supply the patient information leaflet for the formulation given, together with written advice on how much to use, the 4 week limit, and what to do when the course finishes.'],
   ['Counselling',[
     {bullet:'Once a day, to the patchy areas only. Not on your face, genitals or in skin folds.',b:true},
     {bullet:'No more than one 15g tube-worth in a day, and not on more than about a third of your body. Your palm is roughly 1% of your skin.',b:true},
     {bullet:'Wash your hands thoroughly afterwards, so none of it reaches your face or eyes.',b:true},
     {bullet:'Do not cover the treated area with a dressing or wrap.'},
     {bullet:'Do not shower or bathe straight after putting it on.'},
     {bullet:'Keep using your emollients. They are the foundation and you should not stop them.'},
     {bullet:'FIRE RISK FROM EMOLLIENTS AND OINTMENTS. Emollients and paraffin-based ointments, including paraffin-free products, soak into clothing, bedding and dressings and make them catch fire more easily and burn faster. Tell the patient not to smoke, use a naked flame, or go near anything burning, and to wash clothing and bedding often, knowing that washing may not remove the residue completely.',b:true},
     {bullet:'Avoid a lot of sun or sunbeds while you are using this.'},
     {bullet:'THIS IS A 4 WEEK COURSE. Do not keep using it beyond that without seeing your GP.',b:true},
   ]],
   ['When the course ends, and when to get help',[
     {text:'Stopping matters as much as starting.',b:true},
     {bullet:'When you finish, keep using emollients and see your GP as arranged. Do not just stop everything.',b:true},
     {bullet:'GET MEDICAL ADVICE THE SAME DAY if your skin becomes widely red and sore, starts shedding or peeling all over, or you develop crops of small pus-filled spots. That can happen after stopping a strong steroid and needs seeing quickly.',b:true},
     {bullet:'Do not restart the cream yourself to control that. Come back to us or see your GP.',b:true},
     {bullet:'Also seek advice for blurred vision or other eye symptoms, and for increased thirst, needing to pass urine often, constipation, muscle weakness or confusion.',b:true},
   ]],
  ],
 }],

 appendix:[
  {h:'Appendix 1: The three presentations that are emergencies, not flares'},
  {text:'All three are SPC contraindications and all three need same-day assessment. None appeared anywhere in version 001.',b:true},
  {text:''},
  {tbl:[
   ['ERYTHRODERMIC psoriasis',[{bullet:'Widespread redness over most of the body, with scaling and shedding.'},{bullet:'The patient often feels cold, shivery or unwell, and may be tachycardic.'},{bullet:'Fluid, heat and protein loss, and risk of sepsis and cardiac failure.'},{bullet:'SAME-DAY EMERGENCY REFERRAL. Do not supply.',b:true}]],
   ['GENERALISED PUSTULAR psoriasis',[{bullet:'Crops or sheets of small sterile pustules on red, tender skin.'},{bullet:'Often with fever and feeling unwell.'},{bullet:'Can be precipitated by stopping a potent topical steroid.',b:true},{bullet:'SAME-DAY EMERGENCY REFERRAL. Do not supply.',b:true}]],
   ['EXFOLIATIVE psoriasis',[{bullet:'Widespread peeling or shedding of skin in sheets.'},{bullet:'SAME-DAY REFERRAL. Do not supply.',b:true}]],
   ['GUTTATE psoriasis (not an emergency, but not for this PGD)',[{bullet:'Many small drop-shaped lesions, often on the trunk, frequently following a streptococcal sore throat.'},{bullet:'There is no experience with this product in guttate psoriasis. Refer.'}]],
   ['Localised pustular psoriasis of palms and soles',[{bullet:'Pustules confined to palms and soles.'},{bullet:'Still a contraindication to this product. Refer, though not as an emergency unless the patient is unwell.'}]],
  ]},
  {text:''},
  {h:'Appendix 2: Estimating body surface area'},
  {bullet:'The patient’s whole palm including the fingers is roughly 1% of their body surface.'},
  {bullet:'30% is roughly thirty palms. In practice, if psoriasis covers more than about a third of the body, refer.'},
  {bullet:'Record the estimate as a percentage, not as "extensive" or "limited".',b:true},
  {bullet:'The 30% limit exists because of calcipotriol and the risk of hypercalcaemia, not because of the steroid.'},
  {text:''},
  {h:'Appendix 3: Key references'},
  {bullet:'Summary of Product Characteristics for Dovobet ointment, Dovobet gel, Enstilar cutaneous foam and Wynzora cream, and their generic equivalents, current versions.'},
  {bullet:'NICE CKS: Psoriasis.'},
  {bullet:'British National Formulary.'},
  {bullet:'NICE Medicines Practice Guideline 2 (MPG2): Patient Group Directions, https://www.nice.org.uk/guidance/mpg2'},
 ],

 version:'v003',
 supersedes:'Version 002, 8 September 2026',
 validFrom:'9 September 2026',
 expiry:'31 July 2027',
 sigDate:'9 September 2026',
 chDate:'9 September 2026',
 changes:[
  'The practitioner Agreement to practise page, the premises block and the practitioner signature table are restored, together with the standard governance requirements: SPC and BNF familiarity, MHRA safety alerts, CPD and appraisal, indemnity, and capacity and consent. Every version 001 document carried them; no document produced by the current generator did, through one omission in one function that affected 15 live documents. Raised as blocking by an adopting pharmacy.',
  'The fire risk warning for emollients and paraffin-based ointments is restored to the counselling. Emollients, including paraffin-free ones, soak into fabric and make it burn faster. Version 001 carried the warning and version 002 lost it. Found by comparing this document against the archived version 001, not by anyone noticing.',
  'Erythrodermic, exfoliative and pustular psoriasis added as absolute exclusions and identified as same-day emergencies, with Appendix 1 describing how to recognise each. All three are SPC contraindications and none was mentioned anywhere in version 001.',
  'Guttate psoriasis excluded, there being no experience with this product in that form.',
  'Rebound on discontinuation addressed for the first time. Stopping a potent topical corticosteroid in psoriasis can precipitate generalised pustular psoriasis, and version 001 said nothing about it to the pharmacist or the patient. Counselling and a same-day referral trigger are now required.',
  'Repeat supply capped. Version 001 permitted repeats "where previous response was appropriate" with no limit, which is indefinite supply of a potent steroid without review. Now one 4 week course, a further course only where the GP has reviewed since, and a maximum of three courses in any 12 months.',
  'Known disorders of calcium metabolism added as an exclusion, an SPC contraindication that was absent.',
  'The SPC contraindication list completed: parasitic skin infection, skin manifestations of tuberculosis or syphilis, perioral dermatitis, atrophic skin, striae atrophicae, fragility of skin veins, ichthyosis, and ulcers or wounds. Version 001 listed only viral, fungal and bacterial infections, rosacea and acne.',
  'Concurrent use of another topical corticosteroid on the same area added as an exclusion.',
  '30% body surface limit moved from the dosing note into the inclusion and exclusion criteria, with Appendix 2 on estimating it by palm.',
  'Maximum 15g in any one day stated as the operative limit, this being the SPC figure that protects against hypercalcaemia.',
  'Formulations set out individually with a requirement to check the formulation is licensed for the site treated, and a note that Xamiol gel is discontinued.',
  'Visual disturbance added, with referral to an ophthalmologist for possible cataract, glaucoma or central serous chorioretinopathy.',
  'Secondary infection of plaques handled: treat the infection first, and stop the corticosteroid if infection worsens.',
  'Records must now carry the form of psoriasis with the emergency presentations expressly excluded, the body surface percentage and how it was estimated, which formulation and whether it is licensed for the site, whether this is a first or repeat course with the GP review date, and that the rebound advice was given.',
 ],
 prior:[
  ['001','Development and issue of new PGD. Calcipotriol with betamethasone, adults 18 and over, mild to moderate plaque psoriasis. The product and strength were correct; the contraindications, the rebound risk and the limit on repeat supply were not.'],
 ],
};

Packer.toBuffer(build(d)).then(b=>{fs.writeFileSync('psoriasis-v003-SIGNED.docx',b);console.log('psoriasis '+d.version+' docx bytes',b.length);});
