SUMMARIES_PART = {
 "b12-injection": {
  "title": "Summary of NICE and SmPC guidance for vitamin B12 deficiency treated with hydroxocobalamin injection and folic acid",
  "source": "Vitamin B12 deficiency in over 16s: diagnosis and management, NICE guideline NG239, published 6 March 2024. Hydroxocobalamin 1mg/ml Solution for Injection, Summary of Product Characteristics, ADVANZ Pharma (Mercury Pharmaceuticals Ltd, PL 12762/0008), text revised 23 January 2024, emc updated 27 January 2025. Folic Acid 5mg Tablets, Summary of Product Characteristics, Wockhardt UK Ltd (PL 29831/0097), text revised 4 July 2018. Summarised 10 September 2026.",
  "sections": [
   ("Symptoms and who is at risk", [
    "NICE states that the symptoms and signs of vitamin B12 deficiency vary from person to person and are often not exclusive to the deficiency.",
    "Common symptoms and signs listed by NICE are abnormal findings on a blood count such as anaemia or macrocytosis, cognitive difficulties such as difficulty concentrating or short-term memory loss, eyesight problems related to optic nerve dysfunction, glossitis, neurological or mobility problems related to peripheral neuropathy or to central nervous system disease including myelopathy (balance issues and falls, impaired gait, pins and needles or numbness), symptoms of anaemia suggesting iron treatment is not working in pregnancy or breastfeeding, and unexplained fatigue.",
    "NICE says not to rule out the diagnosis solely because anaemia or macrocytosis is absent, and to be aware that the deficiency can be associated with mental health problems including depression, anxiety or psychosis.",
    "Common risk factors listed by NICE are a diet low in vitamin B12 (for example vegan diets or diets excluding animal-source foods, food allergy, difficulty buying or preparing food, low income or a restricted diet), a family history of vitamin B12 deficiency or an autoimmune condition, atrophic gastritis affecting the gastric body, coeliac disease or another autoimmune condition, certain medicines (colchicine, H2-receptor antagonists, metformin, phenobarbital, pregabalin, primidone, proton pump inhibitors and topiramate), previous abdominal or pelvic radiotherapy, previous gastrointestinal surgery including many bariatric operations, gastrectomy or terminal ileal resection, and recreational nitrous oxide use.",
    "NICE states that deficiency is highly likely after total gastrectomy or complete terminal ileal resection if the person is not receiving oral or intramuscular replacement.",
    "NICE recommends offering an initial diagnostic test to people with at least one common symptom or sign and at least one common risk factor, and using clinical judgement for people with a symptom or sign but no risk factor.",
   ]),
   ("How deficiency is confirmed", [
    "NICE recommends either total B12 (serum cobalamin) or active B12 (serum holotranscobalamin) as the initial test, except in pregnancy (use active B12) and where recreational nitrous oxide use is the suspected cause (use plasma homocysteine or serum methylmalonic acid).",
    "Blood samples for diagnostic tests should be taken before starting vitamin B12 replacement.",
    "NICE's thresholds for total B12 are: less than 180 nanograms per litre (133 pmol per litre) is confirmed deficiency, between 180 and 350 nanograms per litre (133 to 258 pmol per litre) is an indeterminate result with possible deficiency, and more than 350 nanograms per litre (258 pmol per litre) suggests deficiency is unlikely.",
    "The corresponding active B12 thresholds are less than 25 pmol per litre (confirmed deficiency), 25 to 70 pmol per litre (indeterminate) and more than 70 pmol per litre (deficiency unlikely).",
    "NICE says that where there is substantial local variation in validated total B12 thresholds, the thresholds set by the testing laboratory should be used, and that people of Black ethnicity may have a higher reference range for serum vitamin B12.",
    "For symptomatic people with an indeterminate result, NICE says to consider a further test for serum methylmalonic acid, and to consider starting replacement while waiting for that result if the person has a condition that may deteriorate rapidly (for example ataxia or anaemia), an irreversible cause such as autoimmune gastritis, surgery that can cause deficiency, or is pregnant or breastfeeding.",
    "NICE advises caution in interpreting results in people already using over-the-counter vitamin B12 preparations (which may raise levels without fully treating a deficiency) and in people taking the combined oral contraceptive pill (which can lower total B12 without causing a deficiency).",
    "The hydroxocobalamin SmPC states that it is advisable to confirm the diagnosis of vitamin B12 deficiency before giving hydroxocobalamin, and that indiscriminate administration may mask the true diagnosis.",
    "NICE says not to delay replacement while waiting for test results in people with suspected megaloblastic anaemia and neurological symptoms, especially those related to sub-acute combined degeneration of the spinal cord.",
   ]),
   ("Identifying the cause", [
    "NICE recommends considering an anti-intrinsic factor antibody test where autoimmune gastritis is suspected, unless the person has previously had a positive test or an operation that could affect absorption.",
    "A negative anti-intrinsic factor antibody result does not rule out autoimmune gastritis, and NICE lists further investigations (anti-gastric parietal cell antibody, gastrin, CobaSorb test, gastroscopy with gastric body biopsy) where suspicion persists.",
    "NICE recommends serological testing for coeliac disease where the cause remains unknown after further investigation.",
    "NICE explains that it does not use the term pernicious anaemia for autoimmune gastritis, because pernicious anaemia in its true sense (life-threatening anaemia) is now extremely rare.",
   ]),
   ("When intramuscular replacement is indicated rather than oral", [
    "NICE recommends offering lifelong intramuscular vitamin B12 replacement where autoimmune gastritis is the cause or suspected cause, or the person has had a total gastrectomy or a complete terminal ileal resection.",
    "Where malabsorption has another cause (for example coeliac disease, partial gastrectomy or some forms of bariatric surgery), NICE says to offer replacement and consider intramuscular instead of oral; if oral replacement is used for malabsorption the dosage should be at least 1 mg a day.",
    "For medicine-induced deficiency and for deficiency caused by recreational nitrous oxide use, NICE says to offer either intramuscular or oral replacement based on clinical judgement and the person's preference, and to advise the person to stop using nitrous oxide.",
    "For dietary deficiency NICE says to consider oral replacement, but to consider intramuscular injections instead where the person has another condition that may deteriorate rapidly (for example a neurological or haematological condition), or where there are concerns about adherence (for example older people with multimorbidity or frailty, delirium or cognitive impairment, or social issues such as homelessness).",
    "Where the cause is uncertain and malabsorption is not suspected, NICE says to offer replacement and consider oral instead of intramuscular, reviewing the response at the first follow-up.",
    "If vitamin B12 deficiency is diagnosed in pregnancy or breastfeeding and autoimmune gastritis is suspected, NICE says to start intramuscular replacement without waiting for the antibody test result.",
   ]),
   ("Hydroxocobalamin regimens as stated in the SmPC", [
    "NICE does not set out a hydroxocobalamin dosing schedule; recommendation 1.6.11 refers to increasing the frequency of injections in line with the summary of product characteristics, so the regimen below is taken from the SmPC.",
    "The SmPC's licensed indications are Addisonian pernicious anaemia, prophylaxis and treatment of other macrocytic anaemias associated with vitamin B12 deficiency, tobacco amblyopia and Leber's optic atrophy.",
    "For Addisonian pernicious anaemia and other macrocytic anaemias without neurological involvement the SmPC gives initially 250 to 1000 micrograms intramuscularly on alternate days for one or two weeks, then 250 micrograms weekly until the blood count is normal, with maintenance of 1000 micrograms every two to three months.",
    "With neurological involvement the SmPC gives initially 1000 micrograms on alternate days as long as improvement is occurring, with maintenance of 1000 micrograms every two to three months.",
    "For prophylaxis of macrocytic anaemia associated with vitamin B12 deficiency resulting from gastrectomy, some malabsorption syndromes and strict vegetarianism, the SmPC gives 1000 micrograms every two or three months.",
    "The method of administration is intramuscular injection; the only contraindication is hypersensitivity to the active substance or any excipient.",
    "The SmPC states that hydroxocobalamin injection should not be used for the treatment of megaloblastic anaemia of pregnancy, and that it is secreted into breast milk but is unlikely to harm the infant.",
    "The SmPC notes that treatment usually results in rapid haematological improvement, but that neurological symptoms respond more slowly.",
   ]),
   ("Folic acid and the rule about treating B12 first", [
    "The folic acid 5 mg SmPC states that folic acid should not be administered for the treatment of pernicious anaemia or undiagnosed megaloblastic anaemia without sufficient amounts of vitamin B12, because folic acid alone will not prevent and may precipitate subacute combined degeneration of the spinal cord, so a full clinical diagnosis should be made before initiating treatment.",
    "The folic acid SmPC adds that folic acid may worsen the symptoms of co-existing vitamin B12 deficiency and should never be used to treat anaemia without a full investigation of the cause.",
    "The hydroxocobalamin SmPC states that if megaloblastic anaemia fails to respond, folate metabolism should be investigated, and that doses in excess of 10 micrograms daily may produce a haematological response in patients with folate deficiency.",
    "The folic acid SmPC dose for folate-deficient megaloblastic anaemia in adults is 5 mg daily for 4 months, with up to 15 mg daily possibly necessary in malabsorption states; the dose for drug-induced folate deficiency is 5 mg daily.",
    "Folic acid is contraindicated in patients with malignant disease unless megaloblastic anaemia is due to folic acid deficiency, and the SmPC advises caution in patients who may have folate-dependent tumours.",
    "Interactions listed in the folic acid SmPC include reduced absorption with sulfasalazine, cholestyramine and aluminium or magnesium antacids, reduced effect with trimethoprim or sulfonamides (which may be serious in megaloblastic anaemia), reduced serum levels of phenytoin, phenobarbital and primidone, and a combination with fluorouracil that should be avoided.",
    "Reported adverse effects of folic acid are rare allergic reactions (including anaphylaxis) and gastrointestinal effects such as abdominal distension, flatulence, anorexia and nausea.",
   ]),
   ("Adverse effects and monitoring of hydroxocobalamin", [
    "The hydroxocobalamin SmPC states that regular monitoring of the blood is recommended, and that cardiac arrhythmias secondary to hypokalaemia have been reported during initial therapy, so plasma potassium should be monitored during this period.",
    "Adverse effects listed (all with frequency not known) include hypersensitivity reactions such as rash, itching and exanthema, anaphylaxis, initial hypokalaemia, headache, paraesthesia, tremor, nausea, vomiting, diarrhoea, fever, chills, hot flushes, dizziness, malaise, injection site reactions, acneiform and bullous eruptions, chromaturia, and reactive thrombocytosis during the first weeks of use in megaloblastic anaemia.",
    "The SmPC notes that parenteral chloramphenicol may attenuate the effect of hydroxocobalamin and that oral contraceptives may lower serum hydroxocobalamin concentration, but says these interactions are unlikely to be of clinical significance.",
   ]),
   ("Follow-up, information and referral", [
    "NICE recommends explaining that symptoms could start to improve within 2 weeks but this may take up to 3 months, that symptoms may get worse initially before improving, and when to seek medical help if symptoms do not improve, get worse, return or are new.",
    "NICE recommends an initial follow-up at 3 months after starting treatment (earlier depending on severity), or at 1 month if the person is pregnant or breastfeeding.",
    "NICE says not to repeat the initial diagnostic test in people receiving intramuscular replacement.",
    "If symptoms have not sufficiently improved on intramuscular treatment, NICE says to increase the frequency of injections if needed in line with the SmPC, think about alternative diagnoses, and agree a date for reassessment.",
    "For an irreversible cause such as autoimmune gastritis, NICE says to continue lifelong injections even if symptoms have resolved; where a reversible cause has been resolved and symptoms have improved, NICE says to think about stopping or reducing the frequency of injections.",
    "NICE states that people with autoimmune gastritis are at higher risk of gastric neuroendocrine tumours and may be at higher risk of gastric adenocarcinoma, and that new or worsening upper gastrointestinal symptoms should prompt consideration of referral for endoscopy in line with NICE's suspected cancer guideline.",
    "NICE also recommends explaining that people with some causes of deficiency, such as autoimmune gastritis, will need lifelong replacement, and that it is important to continue treatment as advised.",
   ]),
   ("What the sources do not say", [
    "NICE NG239 does not give a hydroxocobalamin dose, injection frequency or loading schedule; it refers to the SmPC for this.",
    "NICE NG239 does not state the rule that vitamin B12 must be replaced before or alongside folic acid; that rule comes from the folic acid and hydroxocobalamin SmPCs.",
    "The hydroxocobalamin SmPC does not give a specific number of loading doses for the neurological regimen beyond continuing alternate-day injections as long as improvement is occurring.",
    "The folic acid SmPC does not give a threshold serum or red cell folate value for diagnosing folate deficiency, and NICE NG239 does not cover folate testing.",
   ]),
  ],
 },
 "sleep-melatonin": {
  "title": "Summary of SmPC and NICE CKS guidance for prolonged-release melatonin (Circadin) in short-term insomnia in adults aged 55 and over",
  "source": "Circadin 2 mg prolonged-release tablets, Summary of Product Characteristics, Flynn Pharma Ltd for RAD Neurim Pharmaceuticals EEC SARL (PLGB 52348/0002), text revised 1 January 2021, emc updated 11 February 2025. NICE Clinical Knowledge Summary: Insomnia (Scenario: Managing insomnia and Prescribing information: Prolonged-release melatonin), last revised June 2026. Summarised 10 September 2026.",
  "sections": [
   ("Licensed indication and age", [
    "The Circadin SmPC states that it is indicated as monotherapy for the short-term treatment of primary insomnia characterised by poor quality of sleep in patients who are aged 55 or over.",
    "The SmPC explains the rationale as the role of melatonin in sleep and circadian rhythm regulation and the age-related decrease in endogenous melatonin production, so that melatonin may improve sleep quality particularly in patients over 55 with primary insomnia.",
    "The safety and efficacy of Circadin in children aged 0 to 18 years has not been established.",
    "NICE CKS says that for short-term insomnia (less than 3 months) where sleep hygiene has failed, daytime impairment is severe and insomnia is not likely to resolve soon, cognitive behavioural therapy for insomnia should be offered, with adjunctive short-term hypnotic treatment (a z-drug, or prolonged-release melatonin if over 55 years of age) considered.",
    "NICE CKS says that for people over 55 with persistent insomnia, treatment with prolonged-release melatonin may be considered, with a recommended maximum duration of 13 weeks.",
    "NICE CKS also states that hypnotics should not be prescribed routinely and should be used only for short courses if the person is acutely distressed, and that over-the-counter treatments for insomnia should not be recommended.",
   ]),
   ("Dose, timing and duration", [
    "The recommended dose is 2 mg once daily, taken 1 to 2 hours before bedtime and after food.",
    "The SmPC states that this dosage may be continued for up to thirteen weeks.",
    "In the clinical trials described in the SmPC, patients received Circadin 2 mg every evening for 3 weeks, and a further trial showed the benefit observed after 3 weeks was maintained for up to 3 months.",
    "Tablets should be swallowed whole to maintain the prolonged-release properties; crushing or chewing should not be used to facilitate swallowing.",
    "NICE CKS gives the same dose: 2 mg once daily, 1 to 2 hours before bedtime and after food, for up to 13 weeks, for adults aged 55 years and over.",
    "The SmPC notes that food delays absorption, with a later and lower peak plasma concentration in the fed state.",
   ]),
   ("Contraindications and cautions", [
    "The only contraindication in the SmPC is hypersensitivity to melatonin or to any of the excipients.",
    "The SmPC states that there is no experience of use in patients with liver impairment, that endogenous melatonin levels are markedly elevated in hepatic impairment because of decreased clearance, and that Circadin is therefore not recommended in patients with hepatic impairment.",
    "The SmPC states that no clinical data exist on use in individuals with autoimmune diseases, and Circadin is therefore not recommended in patients with autoimmune diseases.",
    "The effect of renal impairment on melatonin pharmacokinetics has not been studied and the SmPC advises caution in such patients.",
    "Circadin contains lactose (80 mg per tablet); patients with rare hereditary problems of galactose intolerance, the LAPP lactase deficiency or glucose-galactose malabsorption should not take it.",
    "The SmPC states that Circadin may cause drowsiness and should be used with caution if the effects of drowsiness are likely to be associated with a risk to safety.",
    "The SmPC states that Circadin has moderate influence on the ability to drive and use machines.",
    "NICE CKS says not to prescribe prolonged-release melatonin to people with autoimmune disease or hepatic impairment, and to prescribe with caution in renal impairment and in people with susceptibility to seizures because of a risk of increased seizure frequency.",
    "NICE CKS advises telling the person not to drive if they feel sleepy, and that the DVLA must be informed if excessive sleepiness from any condition or medication is having, or is likely to have, an adverse effect on driving.",
    "The SmPC states that use in pregnancy and in women intending to become pregnant is not recommended because of the lack of clinical data, and that breastfeeding is not recommended during treatment because exogenous melatonin is probably secreted into human milk.",
   ]),
   ("Interactions", [
    "The SmPC states that melatonin metabolism is mainly mediated by CYP1A enzymes, so interactions arising from other substances' effects on CYP1A enzymes are possible.",
    "Fluvoxamine increases melatonin levels (a 17-fold higher AUC and a 12-fold higher serum Cmax) by inhibiting its metabolism by CYP1A2 and CYP2C19; the SmPC says the combination should be avoided.",
    "Caution should be exercised with 5- or 8-methoxypsoralen and with cimetidine, both of which increase melatonin levels by inhibiting its metabolism.",
    "Caution should be exercised in patients on oestrogens (for example contraceptive or hormone replacement therapy), which increase melatonin levels by inhibiting its metabolism by CYP1A1 and CYP1A2.",
    "CYP1A2 inhibitors such as quinolones may increase melatonin exposure; CYP1A2 inducers such as carbamazepine and rifampicin may reduce plasma concentrations of melatonin.",
    "Cigarette smoking may decrease melatonin levels because of induction of CYP1A2.",
    "Alcohol should not be taken with Circadin because it reduces the effectiveness of Circadin on sleep.",
    "Circadin may enhance the sedative properties of benzodiazepines and non-benzodiazepine hypnotics such as zaleplon, zolpidem and zopiclone; in a clinical trial co-dosing with zolpidem increased impairment of attention, memory and co-ordination compared with zolpidem alone.",
    "Co-administration with imipramine increased feelings of tranquillity and difficulty performing tasks, and with thioridazine increased feelings of muzzy-headedness, although no clinically significant pharmacokinetic interactions were found.",
    "NICE CKS lists the same interactions: alcohol, opioids and other CNS depressants (which can affect the ability to perform skilled tasks), fluvoxamine (avoid), quinolones and oestrogens (caution), carbamazepine and rifampicin (may reduce melatonin levels), and benzodiazepines and z-drugs (may enhance sedation and side effects).",
   ]),
   ("Adverse effects", [
    "In clinical trials 48.8% of patients receiving Circadin reported an adverse reaction compared with 37.8% on placebo, but the rate of adverse reactions per 100 patient-weeks was higher for placebo than for Circadin.",
    "The SmPC says the most common adverse reactions were headache, nasopharyngitis, back pain and arthralgia, which were common in both the Circadin and placebo groups.",
    "Uncommon adverse reactions listed include irritability, nervousness, restlessness, insomnia, abnormal dreams, nightmares, anxiety, migraine, headache, lethargy, psychomotor hyperactivity, dizziness, somnolence, hypertension, abdominal pain, dyspepsia, mouth ulceration, dry mouth, nausea, hyperbilirubinaemia, dermatitis, night sweats, pruritus, rash, dry skin, pain in extremity, menopausal symptoms, asthenia, chest pain, glycosuria, proteinuria, abnormal liver function tests and weight gain.",
    "Rare adverse reactions listed include herpes zoster, leukopenia, thrombocytopenia, mood alteration, aggression, agitation, depression, syncope, memory impairment, disturbance in attention, restless legs syndrome, poor quality sleep, visual disturbance, vertigo, angina pectoris, palpitations, hot flush, gastrointestinal upset, priapism, prostatitis, fatigue and thirst; hypersensitivity reactions, angioedema and galactorrhoea are listed with frequency not known.",
    "In overdose, somnolence is the most reported event; the SmPC says drowsiness is to be expected, clearance is expected within 12 hours and no special treatment is required.",
    "The SmPC states that when treatment stopped in trials, sleep variables gradually returned to baseline with no rebound, no increase in adverse reactions and no increase in withdrawal symptoms.",
   ]),
   ("What to tell the patient", [
    "Take one 2 mg tablet once a day, 1 to 2 hours before bedtime and after food, swallowed whole and not crushed or chewed.",
    "The SmPC limits treatment to a maximum of thirteen weeks, and NICE CKS gives the same 13-week maximum.",
    "Do not drink alcohol with Circadin, because it reduces the effect on sleep.",
    "Circadin may cause drowsiness; use caution with driving and other activities where drowsiness could be a safety risk, and do not drive if sleepy.",
    "NICE CKS advises offering sleep hygiene advice, including a comfortable sleep environment, avoiding screens for at least an hour before bed, regular sleep schedules, avoiding daytime naps, avoiding caffeine after midday and nicotine, alcohol and large meals within 2 hours of bedtime, and avoiding vigorous exercise within an hour of bedtime.",
    "NICE CKS recommends arranging follow-up in 2 to 4 weeks depending on the clinical situation, and reassessing for alternative diagnoses and the need for referral if symptoms have not improved.",
    "NICE CKS says to refer to a sleep clinic or a specialist in sleep medicine or neurology if another sleep disorder such as a parasomnia, narcolepsy or obstructive sleep apnoea is suspected, or there is doubt about the diagnosis, and to seek specialist advice if primary care treatment has failed or the person is in an occupational at-risk group such as professional drivers.",
   ]),
   ("What the sources do not say", [
    "The Circadin SmPC does not define short-term insomnia in weeks; the 3-week figure comes from the duration of its clinical trials rather than from a dosing instruction.",
    "The Circadin SmPC does not state a caution about seizures; that caution appears only in NICE CKS.",
    "NICE CKS does not give a separate list of contraindications for melatonin in the managing insomnia scenario beyond the general instruction not to prescribe hypnotics to older people or to women who are pregnant or breastfeeding; its melatonin-specific advice is in the prescribing information page.",
    "Neither source gives advice on repeat courses after 13 weeks.",
   ]),
  ],
 },
 "ed": {
  "title": "Summary of BSSM and SmPC guidance for sildenafil and tadalafil in erectile dysfunction in adult men",
  "source": "British Society for Sexual Medicine Guidelines on the Management of Erectile Dysfunction in Men 2017, Hackett G, Kirby M, Wylie K, Heald A, Ossei-Gerning N, Edwards D, Muneer A, Journal of Sexual Medicine 2018 (bssm.org.uk). Sildenafil Mylan 50 mg film-coated tablets, Summary of Product Characteristics, Viatris (PL 55183/0004), text revised May 2022, emc updated 28 July 2022. Cialis 10 mg film-coated tablets (tadalafil), Summary of Product Characteristics, Eli Lilly and Company Limited (PLGB 14895/0237), text revised 27 January 2026, emc updated 24 February 2026. Summarised 10 September 2026.",
  "sections": [
   ("Erectile dysfunction as a marker of cardiovascular disease", [
    "BSSM defines erectile dysfunction as the persistent inability to attain and/or maintain an erection sufficient for sexual performance.",
    "BSSM states that the risk factors for erectile dysfunction (age, sedentary lifestyle, obesity, smoking, dyslipidaemia and the metabolic syndrome) are very similar to the established risk factors for cardiovascular disease, and that erectile dysfunction itself is a cardiovascular risk factor conferring a risk equivalent to a current moderate level of smoking.",
    "BSSM describes erectile dysfunction as a sentinel marker for future cardiovascular events, occurring 3 to 5 years before an event, because the penile arteries are significantly smaller than the main coronary arteries.",
    "BSSM states that a man with erectile dysfunction and no cardiac symptoms is a cardiac patient until proven otherwise, and that all men with unexplained erectile dysfunction should have a thorough evaluation with any coronary heart disease risk factors addressed.",
    "BSSM says that measurement of fasting glucose and/or glycated haemoglobin, lipid profile and morning total testosterone should be considered mandatory in all newly presenting patients, because erectile dysfunction may be the first symptom of diabetes in up to 20% and hypogonadism is a treatable cause that may make men non-responsive to PDE5 inhibitors.",
    "BSSM recommends a comprehensive medical, sexual and relationship history, a focused physical examination in all cases including blood pressure, heart rate, waist circumference and weight, and a genital examination.",
    "Both SmPCs state that a medical history and physical examination should be undertaken to diagnose erectile dysfunction and determine potential underlying causes before pharmacological treatment is considered.",
   ]),
   ("BSSM cardiovascular risk stratification", [
    "BSSM states that the cardiac risk of sexual activity in properly assessed and advised patients with cardiovascular disease is minimal, and that sexual activity is no more stressful to the heart than many common daily activities.",
    "BSSM's table of metabolic equivalents gives sexual intercourse with an established partner as 2 to 3 METs in the lower (normal) range and 5 to 6 METs for vigorous activity, comparable with walking 1 mile in 20 minutes on the level (3 to 4 METs), lifting and carrying 9 to 20 kg (4 to 5 METs), golf (4 to 5 METs), digging in the garden (3 to 5 METs) and heavy housework such as making beds or scrubbing floors (3 to 6 METs).",
    "Low risk in the BSSM table comprises controlled hypertension, asymptomatic men with 3 or fewer risk factors for coronary artery disease (excluding age and gender), mild valvular disease, minimal or mild stable angina, post-successful revascularisation and heart failure NYHA class I; these men should be managed within primary care with treatment options reviewed with the patient and, where possible, his partner.",
    "Intermediate risk comprises recent myocardial infarction or stroke within the last 6 weeks, asymptomatic men with more than 3 risk factors for coronary artery disease, left ventricular dysfunction or heart failure class II, a murmur of unknown cause, moderate stable angina, heart transplant and recurrent transient ischaemic attacks; BSSM recommends specialised evaluation (for example exercise testing for angina or echocardiography for a murmur) and re-assignment to the low- or high-risk group depending on the outcome.",
    "High risk comprises severe, unstable or refractory angina, uncontrolled hypertension (systolic blood pressure above 180 mmHg), heart failure class III or IV, myocardial infarction or stroke within the last 14 days, high-risk arrhythmias, hypertrophic cardiomyopathy and moderate or severe valve disease; BSSM says these men should be referred for specialised cardiac evaluation and treatment for erectile dysfunction deferred until the cardiac condition is established or specialist evaluation completed.",
    "BSSM states that patients who remain in the high-risk group should not be offered treatment for erectile dysfunction in primary care, and that their management should be supervised by a specialist team that will probably include a cardiologist.",
    "BSSM adds that there is no evidence that currently licensed treatments for erectile dysfunction add to the overall cardiovascular risk in patients with or without previously diagnosed cardiovascular disease.",
   ]),
   ("Red flags and referral", [
    "BSSM lists indications for specialist investigation as young patients who have always had difficulty obtaining or sustaining an erection, patients with a history of trauma, an abnormality of the testicles or penis found on examination, and patients unresponsive to medical therapies who may want surgical treatment.",
    "BSSM says a genital examination is essential where there is a history of rapid onset of pain, deviation of the penis during tumescence, symptoms of hypogonadism or other urological symptoms, and describes Peyronie's disease (a lump in the shaft, pain in the shaft, abnormal angulation of the erect penis).",
    "BSSM recommends that if serum testosterone is borderline or low it should be repeated on a further morning sample with luteinising hormone and prolactin, with discussion with or referral to a specialist clinic if results are abnormal, and that patients with persistent unexplained hyperprolactinaemia should be referred to an endocrinologist.",
    "BSSM states that about 25 to 50% of patients do not respond to PDE5 inhibitors within 12 months, that patients should receive at least 4 and preferably 8 doses of the highest tolerated dose of at least 2 drugs (sequentially, not concurrently) with adequate sexual stimulation before being classed as non-responders, and that inadequate prescribing or instruction is the major cause of failure.",
    "BSSM recommends follow-up ideally within 6 weeks of commencing therapy.",
    "Both SmPCs state that an erection persisting longer than 4 hours requires immediate medical assistance, because untreated priapism can cause penile tissue damage and permanent loss of potency.",
    "Both SmPCs advise that in the event of any sudden visual defect the patient should stop the medicine and consult a physician immediately; the tadalafil SmPC adds the same instruction for sudden decrease or loss of hearing.",
   ]),
   ("PDE5 inhibitor doses, timing, titration and adjustments (SmPCs)", [
    "The recommended sildenafil dose is 50 mg taken as needed approximately one hour before sexual activity; based on efficacy and tolerability the dose may be increased to 100 mg or decreased to 25 mg.",
    "The maximum recommended sildenafil dose is 100 mg and the maximum recommended dosing frequency is once per day.",
    "Sexual stimulation is required for sildenafil to be effective, and if taken with food the onset of activity may be delayed compared with the fasted state.",
    "Sildenafil dosage adjustments are not required in elderly patients aged 65 and over, and the standard dosing applies in mild to moderate renal impairment (creatinine clearance 30 to 80 ml/min).",
    "In severe renal impairment (creatinine clearance below 30 ml/min) and in hepatic impairment such as cirrhosis, a sildenafil dose of 25 mg should be considered, with step-wise increase to 50 mg and up to 100 mg as necessary.",
    "A sildenafil starting dose of 25 mg should be considered in patients receiving CYP3A4 inhibitors and in patients on alpha-blocker therapy, who should be stabilised on the alpha-blocker before sildenafil is started.",
    "The recommended tadalafil dose is 10 mg taken prior to anticipated sexual activity, with or without food; in patients in whom 10 mg does not produce an adequate effect, 20 mg might be tried.",
    "Tadalafil may be taken at least 30 minutes before sexual activity, the maximum dose frequency is once per day, and 10 mg and 20 mg doses are not recommended for continuous daily use.",
    "For patients who anticipate frequent use (at least twice weekly), a once-daily regimen of 5 mg (reducible to 2.5 mg) may be considered, with the appropriateness of continued daily use reassessed periodically.",
    "Dose adjustments are not required in elderly men, in mild to moderate renal impairment, or in diabetes.",
    "In severe renal impairment 10 mg is the maximum recommended dose and once-daily dosing is not recommended.",
    "In hepatic impairment the recommended dose is 10 mg; there are no data on doses above 10 mg in hepatic impairment, and in severe hepatic impairment (Child-Pugh C) clinical data are limited so a careful individual benefit-risk evaluation is required.",
    "The SmPC states it is not known whether tadalafil is effective in patients who have undergone pelvic surgery or radical non-nerve-sparing prostatectomy.",
   ]),
   ("Absolute contraindications", [
    "BSSM states that absolute contraindications to PDE5 inhibitors are regular or intermittent use of nitrates in any form, including amyl nitrite (poppers), nicorandil, and guanylate cyclase stimulators such as riociguat, because combined use could cause unpredictable falls in blood pressure and potentially catastrophic hypotension.",
    "Both SmPCs contraindicate co-administration with nitrates or nitric oxide donors in any form, and with riociguat.",
    "Both SmPCs contraindicate use in men for whom sexual activity is inadvisable, for example patients with severe cardiovascular disorders such as unstable angina or severe cardiac failure.",
    "Both SmPCs contraindicate use in patients who have loss of vision in one eye because of non-arteritic anterior ischaemic optic neuropathy (NAION), regardless of whether the episode was connected with previous PDE5 inhibitor exposure.",
    "The sildenafil SmPC contraindicates use in severe hepatic impairment, hypotension (blood pressure below 90/50 mmHg), a recent history of stroke or myocardial infarction, and known hereditary degenerative retinal disorders such as retinitis pigmentosa, because safety has not been studied in these groups.",
    "The tadalafil SmPC contraindicates use in patients with myocardial infarction within the last 90 days, unstable angina or angina during sexual intercourse, NYHA class 2 or greater heart failure in the last 6 months, uncontrolled arrhythmias, hypotension (below 90/50 mmHg) or uncontrolled hypertension, and stroke within the last 6 months.",
    "The tadalafil SmPC does not list severe hepatic impairment as a contraindication but states that clinical data are limited and a careful individual benefit-risk evaluation should be undertaken.",
   ]),
   ("Cautions", [
    "Both SmPCs state that prescribers should consider the patient's cardiovascular status before initiating treatment, because there is a degree of cardiac risk associated with sexual activity and PDE5 inhibitors have vasodilator properties causing mild, transient decreases in blood pressure.",
    "The sildenafil SmPC identifies patients with increased susceptibility to vasodilators, including those with left ventricular outflow obstruction (aortic stenosis, hypertrophic obstructive cardiomyopathy) and multiple system atrophy with severely impaired autonomic control of blood pressure.",
    "Both SmPCs advise caution in patients with anatomical deformation of the penis (angulation, cavernosal fibrosis or Peyronie's disease) and in conditions predisposing to priapism (sickle cell anaemia, multiple myeloma or leukaemia).",
    "Both SmPCs state that combination with other PDE5 inhibitors or other treatments for erectile dysfunction has not been studied and is not recommended.",
    "The sildenafil SmPC advises use only after careful benefit-risk assessment in patients with bleeding disorders or active peptic ulceration, and states that serious cardiovascular events have been reported post-marketing in temporal association with sildenafil, mostly in patients with pre-existing cardiovascular risk factors.",
    "The tadalafil SmPC reports visual defects including central serous chorioretinopathy and NAION, and cases of sudden hearing loss, and advises patients to stop and seek prompt medical attention if these occur.",
    "BSSM notes that risk factors for NAION (age over 50, heart disease, diabetes, hypertension, dyslipidaemia, nicotine use) are the same factors that make men likely to have erectile dysfunction.",
   ]),
   ("Interactions with alpha-blockers and CYP3A4 inhibitors", [
    "BSSM states that alpha-blockers may interact with PDE5 inhibitors to cause orthostatic hypotension, that sildenafil should be initiated at the lowest dose only if the patient is stabilised on alpha-blocker therapy with dosing separated by at least 4 hours, and that these interactions are rarely clinically significant when the drugs are not started simultaneously.",
    "The sildenafil SmPC says symptomatic hypotension with alpha-blockers is most likely within 4 hours of dosing, that patients should be haemodynamically stable on the alpha-blocker first, that a 25 mg starting dose should be considered, and that patients should be told what to do if postural hypotensive symptoms occur.",
    "The tadalafil SmPC states that the combination of tadalafil and doxazosin is not recommended because it significantly increases the blood pressure-lowering effect for at least twelve hours and may cause syncope; with other alpha-blockers, including alfuzosin and tamsulosin, caution is advised, notably in the elderly, with treatment started at minimal dosage.",
    "BSSM says dose adjustment of all PDE5 inhibitors may be needed in patients over 65, in hepatic impairment, in renal impairment, and with potent CYP3A4 inhibitors such as ritonavir, erythromycin and cimetidine.",
    "The sildenafil SmPC states that CYP3A4 inhibitors (ketoconazole, erythromycin, cimetidine) reduce sildenafil clearance and a 25 mg starting dose should be considered; co-administration with ritonavir is not advised and in any event the dose should not exceed 25 mg within 48 hours.",
    "The tadalafil SmPC advises caution with potent CYP3A4 inhibitors (ritonavir, saquinavir, ketoconazole, itraconazole and erythromycin), and lists clarithromycin and grapefruit juice as other inhibitors expected to increase tadalafil exposure.",
    "Both SmPCs note that CYP3A4 inducers such as rifampicin reduce PDE5 inhibitor exposure; the tadalafil SmPC also names phenobarbital, phenytoin and carbamazepine.",
    "The sildenafil SmPC advises caution when sildenafil is initiated in patients treated with sacubitril/valsartan, and states that nicorandil has a nitrate component with the potential for a serious interaction.",
    "BSSM states that co-administration with antihypertensives produces a small additive drop in blood pressure that does not usually cause significant orthostatic hypotension (8.4/5.5 mmHg for sildenafil, 1.6/0.8 mmHg for tadalafil).",
    "BSSM and the tadalafil SmPC state that if a patient taking a PDE5 inhibitor develops chest pain, nitroglycerine must be withheld for at least 24 hours after sildenafil and at least 48 hours after tadalafil, and then given only under close medical observation.",
   ]),
   ("Adverse effects and what to tell the patient", [
    "The sildenafil SmPC lists headache as very common and dizziness, visual colour distortion, visual disturbance, blurred vision, flushing, hot flush, nasal congestion, nausea and dyspepsia as common.",
    "The tadalafil SmPC lists headache, flushing, nasal congestion, dyspepsia, back pain, myalgia and pain in extremity as common, with incidence increasing with dose; adverse reactions are described as transient and generally mild or moderate.",
    "Both SmPCs state that patients should be aware of how they react to the medicine before driving or operating machinery, since dizziness and altered vision have been reported.",
    "BSSM states that PDE5 inhibitors are not initiators of erection and require sexual stimulation, and that so-called failure is often due to sub-optimal counselling at the first consultation, so the patient should understand how to take the tablets properly and return if dissatisfied.",
    "BSSM states that food, particularly fatty food, interacts most with sildenafil and least with tadalafil, and that no interaction with alcohol has been observed with any PDE5 inhibitor up to moderate concentrations; the tadalafil SmPC notes postural dizziness and orthostatic hypotension in some subjects with larger amounts of alcohol.",
    "BSSM recommends that lifestyle change and risk-factor management (exercise, smoking cessation, weight and lipid control) should accompany all treatment regimens, but that pharmacotherapy should not be withheld because lifestyle changes have not been made.",
    "BSSM states that once sildenafil came off patent it was removed from Schedule 2 so that it can be prescribed irrespective of comorbidities and without restriction on frequency, and that the SmPC allows up to 100 mg in any 24-hour period prior to anticipated sexual activity.",
   ]),
   ("What the sources do not say", [
    "The BSSM guideline's risk stratification figure is presented as an image in the PDF; the categories above are taken from the accompanying table text in the guideline.",
    "The BSSM guideline gives the 6-week and 14-day windows for recent myocardial infarction or stroke in its risk table but does not reconcile these with the SmPC contraindication periods (sildenafil: recent history, undefined; tadalafil: 90 days for myocardial infarction and 6 months for stroke).",
    "Neither SmPC gives a minimum interval between a PDE5 inhibitor dose and an alpha-blocker dose; the 4-hour separation for sildenafil comes from BSSM.",
    "The BSSM guideline does not give tadalafil-specific alpha-blocker advice; that comes from the Cialis SmPC.",
    "Neither source sets a specific upper age limit for treatment or a maximum quantity to supply per consultation.",
   ]),
  ],
 },
 "shingles-treatment": {
  "title": "Summary of Green Book, NICE CKS and SmPC guidance for oral antiviral treatment of herpes zoster (shingles) in adults",
  "source": "Immunisation against infectious disease (the Green Book), chapter 28a Shingles (herpes zoster), UK Health Security Agency, chapter dated 12 August 2025, page last updated 19 August 2025. NICE Clinical Knowledge Summary: Shingles (Scenario: Management), last revised January 2026. Aciclovir 800mg Tablets, Summary of Product Characteristics, Wockhardt UK Ltd (PL 29831/0003), text revised 14 April 2026, emc updated 27 April 2026. Valtrex 500 mg film-coated tablets (valaciclovir), Summary of Product Characteristics, GlaxoSmithKline UK (PL 00003/0352), text revised 18 June 2026, emc updated 30 June 2026. Summarised 10 September 2026.",
  "sections": [
   ("The disease and how it presents", [
    "The Green Book states that shingles is caused by reactivation of latent varicella zoster virus, generally decades after primary infection, and that reactivation is associated with immune senescence or suppression of the immune system, for example immunosuppressive therapy, HIV infection or malignancy.",
    "The risk and severity of shingles increase with age; the Green Book gives an estimated lifetime risk of one in four and, before vaccination, an annual incidence of around 790 to 880 cases per 100,000 in people aged 70 to 79 in England and Wales.",
    "The Green Book describes the first signs as abnormal skin sensations and pain in the affected dermatome, with headache, photophobia, malaise and less commonly fever in the prodromal phase.",
    "Within days or weeks a unilateral vesicular rash typically appears in a dermatomal distribution; in immunosuppressed individuals a rash involving multiple dermatomes may occur.",
    "The affected area may be intensely painful with associated paraesthesia, intense itching is common, and the rash typically lasts between two and four weeks.",
    "The Green Book also notes an increased risk of shingles in people with systemic lupus erythematosus, rheumatoid arthritis, diabetes and Wegener's granulomatosis.",
   ]),
   ("Who benefits from antivirals and the treatment window", [
    "NICE CKS recommends offering oral aciclovir, valaciclovir or famciclovir within 72 hours of rash onset to people aged 50 years and over, people with non-truncal involvement (excluding the head and neck, where admission or specialist advice is indicated), people with moderate or severe pain or moderate or severe rash, people with predisposing skin conditions, and immunocompromised people where clinical judgement supports oral treatment (for example non-severe immunocompromise, localised rash, no eye involvement, not systemically unwell and close follow-up possible).",
    "NICE CKS says to consider antiviral treatment for other people aged under 50 with shingles of the extremities or trunk depending on clinical judgement.",
    "If treatment cannot be started within 72 hours, NICE CKS says to consider starting it up to one week after rash onset, especially where the person is at higher risk of severe shingles or complications (continued vesicle formation, signs of cutaneous, visceral or neurological dissemination, older age, immunocompromise or severe pain).",
    "NICE CKS states that antiviral treatment is not recommended in immunocompetent children.",
    "The valaciclovir SmPC states that treatment should start as soon as possible after diagnosis and that there are no data on treatment started more than 72 hours after onset of the zoster rash.",
    "The aciclovir SmPC states that treatment of herpes zoster yields better results if initiated as soon as possible after the onset of the rash.",
    "The valaciclovir SmPC states that in immunocompromised patients antiviral treatment is suggested for those presenting within one week of vesicle formation or at any time before full crusting of lesions.",
    "The valaciclovir SmPC states that valaciclovir accelerates resolution of pain, reduces the duration and proportion of patients with zoster-associated pain (including post-herpetic neuralgia in patients older than 50), and reduces the risk of ocular complications of ophthalmic zoster.",
   ]),
   ("Doses and course lengths", [
    "The aciclovir SmPC dose for treatment of herpes zoster in adults is 800 mg five times daily at approximately four-hourly intervals, omitting the night-time dose, for seven days.",
    "Aciclovir tablets may be dispersed in a minimum of 50 ml of water or swallowed whole with a little water, and patients on high doses should be adequately hydrated.",
    "The valaciclovir SmPC dose for herpes zoster and ophthalmic zoster in immunocompetent adults is 1000 mg three times daily for seven days (3000 mg total daily dose).",
    "For immunocompromised adults the valaciclovir dose is 1000 mg three times daily for at least seven days and for 2 days following crusting of lesions.",
    "The valaciclovir SmPC indication covers herpes zoster and ophthalmic zoster in immunocompetent adults and herpes zoster in adults with mild or moderate immunosuppression; the aciclovir SmPC indication is treatment of herpes zoster infections.",
    "Both SmPCs state that in severely immunocompromised patients (for example after marrow transplant) or in patients with impaired absorption from the gut, intravenous dosing should be considered.",
   ]),
   ("Renal adjustment", [
    "The aciclovir SmPC states that aciclovir is eliminated by renal clearance so the dose must be adjusted in renal impairment, and that elderly patients are likely to have reduced renal function so the need for dose adjustment must be considered.",
    "For herpes zoster the aciclovir SmPC recommends 800 mg three times daily at approximately eight-hourly intervals for moderate renal impairment (creatinine clearance 10 to 25 ml/minute) and 800 mg twice daily at approximately twelve-hourly intervals for severe renal impairment (creatinine clearance below 10 ml/minute).",
    "The valaciclovir SmPC table for treatment of herpes zoster gives 1000 mg three times daily for creatinine clearance 50 ml/min or above, 1000 mg twice daily for 30 to 49 ml/min, 1000 mg once daily for 10 to 29 ml/min, and 500 mg once daily below 10 ml/min; on intermittent haemodialysis the dose should be given after dialysis.",
    "Both SmPCs state that adequate hydration should be maintained, that the risk of renal impairment is increased by concomitant nephrotoxic drugs, and that elderly patients and patients with renal impairment are at increased risk of neurological side effects and should be closely monitored.",
    "The valaciclovir SmPC lists nephrotoxic medicines requiring caution and renal monitoring, including aminoglycosides, organoplatinum compounds, iodinated contrast media, methotrexate, pentamidine, foscarnet, ciclosporin and tacrolimus.",
    "Both SmPCs state that cimetidine and probenecid, and other drugs competing for active renal tubular secretion, increase aciclovir exposure; the aciclovir SmPC says no dosage adjustment is necessary because of the wide therapeutic index, while the valaciclovir SmPC advises caution at zoster treatment doses.",
    "The valaciclovir SmPC states that dose modification is not required in mild or moderate cirrhosis.",
   ]),
   ("Contraindications and warnings", [
    "Both SmPCs contraindicate use in patients hypersensitive to aciclovir or valaciclovir or to any excipient.",
    "Both SmPCs warn of severe cutaneous adverse reactions (toxic epidermal necrolysis, Stevens-Johnson syndrome, acute generalised exanthematous pustulosis, drug reaction with eosinophilia and systemic symptoms, erythema multiforme); treatment must be stopped immediately if suggestive signs appear and patients who have had such a reaction with aciclovir or valaciclovir must not receive either drug again.",
    "The aciclovir SmPC advises caution in patients with underlying neurological abnormalities, severe hepatic or electrolyte abnormalities, or significant hypoxia, and notes the tablets contain lactose.",
    "The aciclovir SmPC states that caution should be exercised in pregnancy by balancing potential benefits against any possible hazard, noting that the pregnancy registry has not shown an increase in birth defects; the valaciclovir SmPC says valaciclovir should only be used in pregnancy if the potential benefits outweigh the potential risk.",
    "The aciclovir SmPC advises caution in nursing women because aciclovir is detected in breast milk; the valaciclovir SmPC says valaciclovir should be used with caution during breastfeeding and only when clinically indicated.",
    "NICE CKS says to seek specialist advice before prescribing antiviral treatment to a pregnant or breastfeeding woman with shingles.",
    "Common adverse effects in the aciclovir SmPC are headache, dizziness, nausea, vomiting, diarrhoea, abdominal pain, pruritus, rashes including photosensitivity, fever and fatigue; the valaciclovir SmPC lists headache as very common and nausea, dizziness, vomiting, diarrhoea, rashes and pruritus as common.",
    "Both SmPCs describe reversible neurological reactions (confusion, hallucinations, agitation, tremor, convulsions, encephalopathy, coma) usually in patients with renal impairment or other predisposing factors, and renal impairment or acute renal failure that may be associated with crystalluria.",
   ]),
   ("Referral: ophthalmic, immunocompromised, disseminated and pregnancy", [
    "NICE CKS says to admit to hospital or seek immediate specialist advice for shingles in the ophthalmic distribution of the trigeminal nerve, especially with Hutchinson's sign (rash on the tip, side or root of the nose), eye pain, photophobia, reduced corneal sensitivity, visual impairment or an unexplained red eye.",
    "NICE CKS also says to admit or seek immediate specialist advice where serious complications such as meningitis, encephalitis or myelitis are suspected, where the head and neck are affected especially in elderly people, where there are haemorrhagic or necrotic lesions, multisegmental involvement, satellite lesions, mucosal involvement or generalised zoster, where the person is severely immunosuppressed, where an immunocompromised child has shingles, or where there are signs of visceral or central nervous system involvement.",
    "NICE CKS says severely immunocompromised people should be referred for intravenous aciclovir.",
    "The valaciclovir SmPC states that patients with complicated herpes zoster (visceral involvement, disseminated zoster, motor neuropathies, encephalitis and cerebrovascular complications) should be treated with intravenous antiviral therapy, as should immunocompromised patients with ophthalmic zoster or a high risk of dissemination and visceral involvement.",
    "The valaciclovir SmPC says clinical response should be closely monitored, particularly in immunocompromised patients, with intravenous therapy considered when response to oral therapy is insufficient.",
    "NICE CKS says to refer or seek specialist advice if new vesicles are forming after 7 days of oral antiviral treatment or healing is delayed, if a person thought to be immunocompetent has had two episodes of shingles, if shingles recurs in an immunocompromised person, or if pain is inadequately controlled by oral analgesia or a strong opioid is being considered.",
    "The Green Book states that ophthalmic zoster occurs in 10 to 20% of shingles cases, that complications depend on the nerves affected and include paresis, facial palsy and herpes zoster ophthalmicus with keratitis, corneal ulceration, conjunctivitis, retinitis, optic neuritis or glaucoma, and that disseminated disease (pneumonia, hepatitis, encephalitis, disseminated intravascular coagulopathy) is more likely in severely immunosuppressed people with a case fatality of 5 to 15%.",
   ]),
   ("Pain and post-herpetic neuralgia in outline", [
    "The Green Book defines post-herpetic neuralgia as pain that persists for, or appears more than, 90 days after onset of the rash; it is seen more frequently in older people and on average lasts three to six months but can persist longer.",
    "The Green Book gives pre-vaccine estimates of the proportion developing post-herpetic neuralgia after 90 days rising from 9% at age 60 to 64 to 52% at age 85 and over.",
    "NICE CKS recommends paracetamol or an NSAID such as ibuprofen, alone or with a weak opioid such as codeine, for mild to moderate pain in adults, and a choice of amitriptyline (off-label), duloxetine (off-label), gabapentin or pregabalin for moderate to severe pain.",
    "NICE CKS says capsaicin cream may be considered for localised neuropathic pain where oral treatment is to be avoided or is not tolerated, and that oral corticosteroids may be considered in the first 2 weeks after rash onset in immunocompetent adults with localised shingles and severe pain, but only in combination with antiviral treatment.",
    "NICE CKS says to seek specialist advice or refer to the pain team if pain is inadequately controlled by oral analgesia or a strong opioid is being considered, and to see its post-herpetic neuralgia topic for pain persisting after the skin lesions have resolved.",
   ]),
   ("Infectivity advice", [
    "The Green Book states that individuals with active lesions, particularly if immunosuppressed, can transmit varicella zoster virus to susceptible individuals to cause chickenpox, and that there is no evidence that shingles can be acquired from another individual who has chickenpox.",
    "NICE CKS says the person is infectious until all the vesicles have crusted over, approximately 7 days after rash onset.",
    "NICE CKS advises avoiding skin contact with people at high risk of complications (immunocompromised people, newborn babies and elderly people) and with people who have not had chickenpox (especially pregnant women) until the rash crusts over.",
    "NICE CKS advises avoiding sharing clothes and towels, avoiding touching or scratching the rash, washing hands often, wearing loose-fitting clothes, covering lesions not under clothes while the rash is weeping, keeping the rash clean and dry, and avoiding topical antibiotics and adhesive dressings.",
    "NICE CKS advises avoiding work, school or daycare if the rash is weeping and cannot be covered, and seeking medical advice if temperature rises because this may indicate bacterial infection.",
    "The Green Book states that at-risk individuals who have had a significant exposure to shingles require post-exposure management under the varicella chapter and the UKHSA post-exposure prophylaxis guidelines, and that the shingles vaccine is not recommended for the treatment of shingles or post-herpetic neuralgia.",
   ]),
   ("What the sources do not say", [
    "The Green Book chapter is an immunisation chapter and does not give antiviral doses or the 72-hour treatment window; those come from NICE CKS and the SmPCs.",
    "The aciclovir SmPC does not state the 72-hour window explicitly; it says treatment yields better results if started as soon as possible after rash onset.",
    "NICE CKS does not give the antiviral doses or renal dose adjustments in its management scenario; those are taken from the two SmPCs.",
    "Neither SmPC gives a specific age threshold (such as 50 years) for deciding who should receive treatment; that threshold comes from NICE CKS.",
    "Famciclovir is named by NICE CKS as an alternative but was not fetched and is not summarised here.",
   ]),
  ],
 },
}
