SUMMARIES_PART = {
 "impetigo": {
  "title": "Summary of NICE guidance for impetigo",
  "source": "Impetigo: antimicrobial prescribing, NICE guideline NG153, published 26 February 2020; minor wording changes January 2022 to reflect updated advice on the use of macrolides in pregnancy. Summarised 9 September 2026.",
  "sections": [
   ("What impetigo is and how it presents", [
    "NICE describes impetigo as a contagious bacterial infection of the superficial layers of the skin.",
    "The most common bacterial pathogen is Staphylococcus aureus, although infection with Streptococcus pyogenes, or a combination of both pathogens, is also seen.",
    "Impetigo affects all age groups but is most common in young children.",
    "Non-bullous impetigo is characterised by thin-walled vesicles or pustules that rupture quickly, forming a golden-brown crust.",
    "Bullous impetigo is characterised by fluid-filled vesicles and blisters, often over 1 cm in diameter, that rupture leaving a thin, flat, yellow-brown crust.",
    "NICE states that clinical judgement should be used to decide whether impetigo is localised or widespread.",
   ]),
   ("Localised non-bullous impetigo: hydrogen peroxide first", [
    "For people with localised non-bullous impetigo who are not systemically unwell or at high risk of complications, consider hydrogen peroxide 1% cream, applied two or three times a day for 5 days.",
    "NICE notes that other topical antiseptics are available for superficial skin infections but no evidence was found for using them to treat impetigo.",
    "If hydrogen peroxide 1% cream is unsuitable (for example, if the impetigo is around the eyes) or ineffective, offer a short course of a topical antibiotic.",
    "The first-choice topical antibiotic is fusidic acid 2%, applied three times a day for 5 days, with mupirocin 2% three times a day for 5 days as the alternative if fusidic acid resistance is suspected or confirmed.",
    "NICE warns that extended or recurrent use of topical fusidic acid or mupirocin may increase the risk of antimicrobial resistance.",
   ]),
   ("Widespread, bullous or higher-risk impetigo: when an oral antibiotic is indicated", [
    "For widespread non-bullous impetigo in people who are not systemically unwell or at high risk of complications, offer a short course of either a topical or an oral antibiotic; NICE states both are effective.",
    "In choosing between topical and oral treatment, take into account the person's preferences, the practicalities of application (particularly to large areas), possible adverse effects, and previous use of topical antibiotics, because resistance can develop rapidly with extended or repeated use.",
    "Offer a short course of an oral antibiotic to all people with bullous impetigo, and to people with non-bullous impetigo who are systemically unwell or at high risk of complications.",
    "Do not offer combination treatment with a topical and an oral antibiotic.",
    "If impetigo is worsening or has not improved after hydrogen peroxide, offer a topical antibiotic if it remains localised, or a topical or oral antibiotic if it has become widespread.",
    "If impetigo is worsening or has not improved after completing a course of topical antibiotic, offer a short course of an oral antibiotic and consider sending a skin swab for microbiological testing.",
   ]),
   ("Oral antibiotic choice, doses and course length", [
    "The first-choice oral antibiotic is flucloxacillin: adults 500 mg four times a day for 5 days.",
    "Flucloxacillin doses for children (oral solution or capsules) are 62.5 mg to 125 mg four times a day at 1 month to 1 year, 125 mg to 250 mg four times a day at 2 to 9 years, and 250 mg to 500 mg four times a day at 10 to 17 years, each for 5 days.",
    "For penicillin allergy, or if flucloxacillin is unsuitable, in people who are not pregnant, the alternative is clarithromycin: adults 250 mg twice a day for 5 days, which can be increased to 500 mg twice a day if needed for severe infections.",
    "Clarithromycin for children aged 1 month to 11 years is weight-based: under 8 kg 7.5 mg/kg twice a day, 8 to 11 kg 62.5 mg twice a day, 12 to 19 kg 125 mg twice a day, 20 to 29 kg 187.5 mg twice a day, 30 to 40 kg 250 mg twice a day, each for 5 days; at 12 to 17 years, 250 mg twice a day for 5 days, increased to 500 mg twice a day if needed for severe infections.",
    "For penicillin allergy in pregnancy, the alternative is erythromycin 250 mg to 500 mg four times a day for 5 days (in children, 8 to 17 years, 250 mg to 500 mg four times a day for 5 days); NICE states erythromycin is preferred if a macrolide is needed in pregnancy.",
    "A 5-day course is usually appropriate but can be increased to 7 days based on clinical judgement, depending on the severity and number of lesions.",
    "If meticillin-resistant Staphylococcus aureus is suspected or confirmed, consult a local microbiologist.",
    "If flucloxacillin oral solution is not tolerated because of poor palatability, consider capsules.",
    "Take account of local antimicrobial resistance data when available, and see the BNF or BNF for Children for dosing in specific populations such as hepatic or renal impairment, pregnancy and breastfeeding.",
   ]),
   ("Reassessment, referral and seeking advice", [
    "Reassess if symptoms worsen rapidly or significantly at any time, or have not improved after completing a course of treatment.",
    "When reassessing, take account of other possible diagnoses such as herpes simplex, any symptoms or signs suggesting a more serious illness such as cellulitis, and previous antibiotic use which may have led to resistant bacteria.",
    "Refer to hospital people with impetigo and any symptoms or signs suggesting a more serious illness or condition (for example, cellulitis), and people with widespread impetigo who are immunocompromised.",
    "Consider referral or seeking specialist advice for people who have bullous impetigo (particularly babies aged 1 year and under), impetigo that recurs frequently, who are systemically unwell, or who are at high risk of complications.",
    "For impetigo that recurs frequently, send a skin swab for microbiological testing and consider a nasal swab and starting decolonisation treatment.",
    "If a swab has been sent, review the antibiotic choice when results are available and change it according to results if symptoms are not improving, using a narrow-spectrum antibiotic if possible.",
   ]),
   ("Advice to the patient", [
    "Advise people with impetigo, and their parents or carers if appropriate, about good hygiene measures to reduce the spread of impetigo to other areas of the body and to other people.",
    "Advise them to seek medical help if symptoms worsen rapidly or significantly at any time, or have not improved after completing a course of treatment.",
    "NICE notes that impetigo is highly infectious and that treatment limits spread and hastens recovery, which is likely to mean less time off school, nursery or work; the guideline does not itself set out school exclusion periods.",
   ]),
  ],
 },
 "uti": {
  "title": "Summary of NICE guidance for lower urinary tract infection",
  "source": "Urinary tract infection (lower): antimicrobial prescribing, NICE guideline NG109, published 31 October 2018; minor updates July 2019 (nitrofurantoin formulations), May 2022 (recommendation 1.2.1) and May 2025 (links to MHRA advice on nitrofurantoin). Summarised 9 September 2026.",
  "sections": [
   ("What the guideline covers and assessment", [
    "NG109 sets out an antimicrobial prescribing strategy for lower urinary tract infection (also called cystitis) in children, young people and adults who do not have a catheter.",
    "NICE describes lower UTI as an infection of the bladder usually caused by bacteria from the gastrointestinal tract entering the urethra and travelling up to the bladder.",
    "The guideline does not set out a diagnostic list of lower UTI symptoms; it directs that if there are symptoms of pyelonephritis (such as fever) or a complicated UTI, the NICE guideline on acute pyelonephritis should be followed for antibiotic choices.",
    "When deciding on treatment, take account of the severity of symptoms, the risk of complications (higher in people with known or suspected structural or functional abnormality of the genitourinary tract or immunosuppression), previous urine culture and susceptibility results, previous antibiotic use which may have led to resistant bacteria, and the person's preferences.",
    "Give self-care advice to all people with lower UTI.",
   ]),
   ("Back-up versus immediate antibiotic in non-pregnant women", [
    "For women with lower UTI who are not pregnant, consider either a back-up antibiotic prescription (to use if symptoms do not start to improve within 48 hours or worsen at any time) or an immediate antibiotic prescription.",
    "NICE notes that the evidence for back-up prescriptions was only in non-pregnant women with lower UTI where immediate antibiotic treatment was not considered necessary.",
    "When a back-up prescription is given, advise that an antibiotic is not needed immediately, to use the prescription if symptoms do not start to improve within 48 hours or worsen at any time, and about possible adverse effects, particularly diarrhoea and nausea.",
    "When an immediate prescription is given, advise about possible adverse effects (particularly diarrhoea and nausea) and about seeking medical help if symptoms worsen rapidly or significantly, do not start to improve within 48 hours of taking the antibiotic, or the person becomes systemically very unwell.",
   ]),
   ("Antibiotic choice for non-pregnant women aged 16 and over", [
    "First choices: nitrofurantoin (if eGFR is 45 ml/minute or more) 100 mg modified-release twice a day (or, if unavailable, 50 mg four times a day) for 3 days, or trimethoprim 200 mg twice a day for 3 days if there is a low risk of resistance.",
    "A lower risk of trimethoprim resistance is more likely if trimethoprim has not been used in the past 3 months, previous urine culture suggests susceptibility, and in younger people in areas where local data suggest resistance is low; a higher risk is more likely with recent use and in older people in residential facilities.",
    "Second choices (if no improvement on the first choice taken for at least 48 hours, or when the first choice is not suitable): nitrofurantoin as above for 3 days if not already used, pivmecillinam 400 mg initial dose then 200 mg three times a day for a total of 3 days, or fosfomycin 3 g as a single dose sachet.",
    "Take account of local antimicrobial resistance data, check any previous urine culture and susceptibility results and antibiotic prescribing, and see the BNF for use in hepatic or renal impairment and breastfeeding.",
    "Nitrofurantoin may be used with caution if eGFR is 30 to 44 ml/minute only for uncomplicated lower UTI caused by suspected or proven multidrug-resistant bacteria and only if potential benefit outweighs risk; NICE also links to the MHRA advice on monitoring for pulmonary and hepatic adverse reactions to nitrofurantoin.",
    "If a urine sample has been sent for culture, review the antibiotic choice when results are available and change it if the bacteria are resistant and symptoms are not already improving, using a narrow-spectrum antibiotic wherever possible.",
   ]),
   ("Pregnant women, men and children are managed differently", [
    "Offer an immediate antibiotic prescription to pregnant women and to men with lower UTI, and obtain a midstream urine sample before antibiotics are taken for culture and susceptibility testing.",
    "For pregnant women aged 12 years and over, the first choice is nitrofurantoin (if eGFR is 45 ml/minute or more) 100 mg modified-release twice a day (or 50 mg four times a day) for 7 days, avoided at term because it may produce neonatal haemolysis; second choices are amoxicillin 500 mg three times a day for 7 days (only if culture results are available and susceptible) or cefalexin 500 mg twice a day for 7 days.",
    "Asymptomatic bacteriuria is treated with antibiotics in pregnant women because it is a risk factor for pyelonephritis and premature delivery, but is not routinely screened for or treated in non-pregnant women, men, young people and children.",
    "For men aged 16 years and over, the first choices are trimethoprim 200 mg twice a day for 7 days or nitrofurantoin (if eGFR is 45 ml/minute or more) 100 mg modified-release twice a day for 7 days; nitrofurantoin is not recommended where prostate involvement is suspected because it is unlikely to reach therapeutic levels in the prostate.",
    "For men with no improvement on first choice, consider alternative diagnoses and follow the NICE guidelines on acute pyelonephritis or acute prostatitis, basing antibiotic choice on recent culture and susceptibility results.",
    "For children and young people under 16, obtain a urine sample before antibiotics, offer an immediate antibiotic prescription, and follow the NICE guideline on urinary tract infection in under 16s; children under 3 months should be referred to a paediatric specialist.",
   ]),
   ("Reassessment and referral", [
    "Reassess if symptoms worsen rapidly or significantly at any time, or do not start to improve within 48 hours of taking the antibiotic.",
    "At reassessment take account of other possible diagnoses, any symptoms or signs suggesting a more serious illness or condition such as pyelonephritis, and previous antibiotic use.",
    "Send a urine sample for culture and susceptibility testing at reassessment if this has not already been done, and review treatment when results are available.",
    "Refer people aged 16 years and over with lower UTI to hospital if they have any symptoms or signs suggesting a more serious illness or condition (for example, sepsis).",
    "Refer children or young people to hospital in line with the NICE guideline on urinary tract infection in under 16s, and assess and manage children under 5 who present with fever as outlined in the NICE guideline on fever in under 5s.",
   ]),
   ("Self-care advice", [
    "Advise people with lower UTI about using paracetamol for pain, or if preferred and suitable, ibuprofen.",
    "Advise people about drinking enough fluids to avoid dehydration.",
    "NICE states that no evidence was found on cranberry products or urine alkalinising agents to treat lower UTI.",
   ]),
  ],
 },
 "wound-care": {
  "title": "Summary of NICE guidance for cellulitis and infected wounds",
  "source": "Cellulitis and erysipelas: antimicrobial prescribing, NICE guideline NG141, published 27 September 2019; minor changes November 2019 (committee discussion on co-amoxiclav in children) and January 2022 (wording on macrolides in pregnancy). Summarised 9 September 2026.",
  "sections": [
   ("What the guideline covers", [
    "NG141 sets out an antimicrobial prescribing strategy for adults, young people, children and babies aged 72 hours and over with cellulitis and erysipelas.",
    "NICE describes cellulitis and erysipelas as infections of the subcutaneous tissues that usually result from contamination of a break in the skin, characterised by acute localised inflammation and oedema, with erysipelas lesions more superficial and having a well-defined raised margin.",
   ]),
   ("Assessment and differential diagnosis", [
    "To ensure cellulitis and erysipelas are treated appropriately, exclude other causes of skin redness such as an inflammatory reaction to an immunisation or an insect bite, or a non-infectious cause such as chronic venous insufficiency.",
    "Other possible diagnoses NICE lists at reassessment are gout, superficial thrombophlebitis, eczema, allergic dermatitis and deep vein thrombosis.",
    "Before treating, consider drawing around the extent of the infection with a single-use surgical marker pen to monitor progress, and be aware that redness may be less visible on darker skin tones.",
    "Consider a swab for microbiological testing only if the skin is broken and there is a penetrating injury, exposure to water-borne organisms, or the infection was acquired outside the UK.",
    "Features that suggest a more serious illness or condition are lymphangitis, orbital cellulitis, osteomyelitis, septic arthritis, necrotising fasciitis and sepsis.",
    "Infection around the eyes or nose (the triangle from the bridge of the nose to the corners of the mouth, or immediately around the eyes including periorbital cellulitis) is of more concern because of the risk of a serious intracranial complication.",
    "Manage any underlying condition that may predispose to cellulitis, for example diabetes, venous insufficiency, eczema, or oedema (which may be an adverse effect of medicines such as calcium channel blockers).",
   ]),
   ("When antibiotics are indicated", [
    "Offer an antibiotic to people with cellulitis or erysipelas.",
    "When choosing the antibiotic, take account of the severity of symptoms, the site of infection (for example near the eyes or nose), the risk of uncommon pathogens (penetrating injury, water-borne exposure, infection acquired outside the UK), previous swab results, and the person's MRSA status if known.",
    "Give oral antibiotics first line if the person can take oral medicines and the severity of their condition does not require intravenous antibiotics.",
    "Do not routinely offer antibiotic prophylaxis to prevent recurrent cellulitis or erysipelas.",
   ]),
   ("First choice flucloxacillin: doses and course length", [
    "For adults aged 18 years and over, the first-choice antibiotic is oral flucloxacillin 500 mg to 1 g four times a day for 5 to 7 days; NICE noted that in September 2019, 1 g orally four times a day was off label.",
    "For children aged 1 month and over, oral flucloxacillin is 62.5 mg to 125 mg four times a day at 1 month to 1 year, 125 mg to 250 mg four times a day at 2 to 9 years, and 250 mg to 500 mg four times a day at 10 to 17 years, for 5 to 7 days.",
    "Antibiotic choice for children under 1 month should be based on specialist advice.",
    "A longer course, up to 14 days in total, may be needed based on clinical assessment, but skin takes some time to return to normal and full resolution of symptoms at 5 to 7 days is not expected.",
    "If flucloxacillin oral solution is not tolerated because of poor palatability, consider capsules.",
    "The age bands apply to children of average size; the prescriber should use them alongside the severity of the condition and the child's size relative to the average for their age.",
   ]),
   ("Alternatives in penicillin allergy or where flucloxacillin is unsuitable", [
    "For adults, the alternatives are clarithromycin 500 mg twice a day for 5 to 7 days, erythromycin (in pregnancy) 500 mg four times a day for 5 to 7 days, or doxycycline 200 mg on the first day then 100 mg once a day for 5 to 7 days in total.",
    "For children, alternatives are clarithromycin (1 month to 11 years, weight-based: under 8 kg 7.5 mg/kg twice a day, 8 to 11 kg 62.5 mg twice a day, 12 to 19 kg 125 mg twice a day, 20 to 29 kg 187.5 mg twice a day, 30 to 40 kg 250 mg twice a day; 12 to 17 years 250 mg to 500 mg twice a day) for 5 to 7 days, erythromycin in pregnancy at 8 to 17 years 250 mg to 500 mg four times a day for 5 to 7 days, or co-amoxiclav if flucloxacillin is unsuitable but there is no penicillin allergy.",
    "NICE states erythromycin is preferred if a macrolide is needed in pregnancy, for example with true penicillin allergy where the benefits of treatment outweigh the harms.",
    "If infection is near the eyes or nose, the first choice is co-amoxiclav 500/125 mg three times a day for 7 days, with clarithromycin plus metronidazole as the alternative in penicillin allergy, and NICE advises considering specialist advice.",
    "If MRSA is suspected or confirmed, other antibiotics may be appropriate based on microbiological results and specialist advice.",
    "See the BNF or BNF for Children for dosing in hepatic or renal impairment, pregnancy and breastfeeding.",
   ]),
   ("Referral and seeking specialist advice", [
    "Refer people to hospital if they have any symptoms or signs suggesting a more serious illness or condition, such as orbital cellulitis, osteomyelitis, septic arthritis, necrotising fasciitis or sepsis.",
    "Consider referral to hospital, or seek specialist advice, if the person is severely unwell, has infection near the eyes or nose (including periorbital cellulitis), could have uncommon pathogens (penetrating injury, water-borne exposure, infection acquired outside the UK), has spreading infection not responding to oral antibiotics, has lymphangitis, or cannot take oral antibiotics.",
   ]),
   ("Advice to the patient and reassessment", [
    "When prescribing antibiotics, give advice about possible adverse effects, that the skin will take some time to return to normal after the course has finished, and to seek medical help if symptoms worsen rapidly or significantly at any time or do not start to improve within 2 to 3 days.",
    "Reassess if symptoms worsen rapidly or significantly at any time, do not start to improve within 2 to 3 days, or the person becomes systemically very unwell, has severe pain out of proportion to the infection, or has redness or swelling spreading beyond the initial presentation (allowing for some initial spread, and for redness being less visible on darker skin).",
    "At reassessment, take account of other possible diagnoses, any predisposing condition, any features of a more serious illness, any microbiology results, and previous antibiotic use which may have led to resistant bacteria.",
    "Consider taking a swab at reassessment if the skin is broken and this has not already been done; if a swab has been sent, review the antibiotic when results are available and change it if the infection is not improving, using a narrow-spectrum antibiotic if possible.",
   ]),
  ],
 },
}
