SUMMARIES_PART = {
 "japanese-encephalitis": {
  "title": "Summary of Green Book chapter 20 guidance for Japanese encephalitis vaccination",
  "source": ("UKHSA, Immunisation against infectious disease (the Green Book), Chapter 20: Japanese "
             "encephalitis, dated February 2024 (PDF hosted by NaTHNaC on TravelHealthPro and linked "
             "from the GOV.UK publication page, page last updated 6 February 2024). "
             "Summarised 10 September 2026."),
  "sections": [
   ("The disease, its geography and the risk to travellers", [
     "Japanese encephalitis (JE) is a mosquito-borne viral encephalitis caused by a flavivirus and is the leading cause of childhood encephalitis in Asia.",
     "The global incidence is unknown, but an estimated 68,000 clinical cases occur annually in 24 countries with JE risk (World Health Organization, 2019).",
     "JE is endemic in rural areas, especially where rice growing and pig farming coexist, and epidemics occur in rural and occasionally in urban areas.",
     "The highest transmission rates occur during and just after wet seasons when mosquitoes are most active, but seasonal patterns vary within individual countries and from year to year, and cases are also reported outside the normal seasonal period of high transmission.",
     "The disease is not transmitted from person to person.",
     "The incubation period is four to 14 days. Most infections are mild or asymptomatic, but approximately one in 250 infections is estimated to result in severe illness (rapid onset high fever, headache, neck stiffness, disorientation, coma, seizures).",
     "Case fatality rates in those with symptoms can be as high as 30 percent, and permanent sequelae (intellectual, behavioural and other neurological problems such as paralysis, Parkinsonian-like movement disorders, recurrent seizures or inability to speak) are reported in 20 to 30 percent of survivors.",
     "National immunisation campaigns and urban development in the 1960s led to the near-elimination of JE in Japan, South Korea, Singapore and Taiwan, but JE remains endemic in much of the rest of Asia, with China (excluding Taiwan) accounting for 50 percent of cases. In 2022 the first reported JE outbreak in mainland Australia was declared.",
     "There is geographical variation in transmission periods, from all year round to seasonal. In temperate regions of Asia most cases occur in the warm season, when large epidemics can occur. In the tropics and subtropics JE can occur year-round, but transmission often intensifies during the rainy season and pre-harvest period in rice-cultivating regions.",
     "JE is rare in British travellers, but three cases were diagnosed in 2014 and 2015 resulting in severe neurological illness and long-term sequelae. None of these travellers had received JE vaccine despite having indications for it.",
     "Country-specific recommendations and information on the global epidemiology of JE can be found at travelhealthpro.org.uk and travax.nhs.uk.",
     "No specific therapy is available for JE; supportive treatment can significantly reduce morbidity and mortality.",
   ]),
   ("Who the chapter recommends vaccination for", [
     "The objective of JE vaccination is to protect individuals at high risk of exposure during travel or in the course of their occupation.",
     "All travellers should undergo a careful risk assessment that takes into consideration their itinerary, season of travel, duration of stay and planned activities. The risk of JE should then be balanced against the risk of adverse events from vaccination. Travellers should also look at country-specific recommendations and reduce the risk of JE with bite avoidance.",
     "JE vaccine is recommended for those who are going to reside in an area where JE is endemic or epidemic.",
     "Travellers to risk areas in Asia and the Western Pacific region should be immunised if staying for a month or longer in endemic areas during the transmission season, especially if travel will include rural areas.",
     "The chapter's flowchart (Figure 20.1) also lists frequent travel to JE endemic areas and potential exposure to JE in a laboratory as groups for whom JE vaccine is recommended provided there are no contraindications.",
     "Other travellers with shorter exposure periods should be immunised if the risk is considered sufficient; for example, those spending a short period of time in rice fields (where the mosquito vector breeds) or close to pig farming (a reservoir host for the virus) should be considered for vaccination.",
     "The flowchart states that JE vaccine should be considered where there is a shorter exposure period (under one month) but increased risk from the planned itinerary, location and activities (such as visiting rice fields or pig farms), or where there is travel to an endemic area with uncertainties regarding the planned itinerary, location, activities and duration of stay.",
     "JE vaccine is not recommended for those with lower risk itineraries such as shorter stays (under one month) in towns and cities.",
     "Immunisation is recommended for all research laboratory staff who have potential exposure to the virus; worldwide there have been 22 cases of laboratory-acquired JE virus infection.",
     "There are no safety or efficacy data on the use of IXIARO in children under two months of age and it is not usually recommended in this age group in the UK.",
   ]),
   ("The vaccine (IXIARO) and the schedule", [
     "There is currently one licensed vaccine recommended for use in the UK, IXIARO, which is licensed in the UK for individuals aged two months and older.",
     "IXIARO is an inactivated vaccine produced in Vero cells and adsorbed onto an aluminium hydroxide adjuvant to improve its immunogenicity. As the vaccine does not contain live organisms, it cannot cause the disease against which it protects.",
     "IXIARO is available as a 0.5 ml suspension in a pre-filled syringe (Type 1 glass) with a chlorobutyl elastomer plunger stopper.",
     "Children aged two months to under 36 months: the licensed schedule is two doses of 0.25 ml, the first at day 0 and the second 28 days after the first dose. This is half of the standard dose, and the manufacturer's patient information leaflet should be consulted for instructions on discarding half of the vaccine. Full immunity takes up to one week to develop after the second dose.",
     "Children aged three years to 17 years: the licensed schedule is two doses of 0.5 ml, on days 0 and 28. Full immunity takes up to one week to develop after the second dose.",
     "Adults aged 18 years and older: the standard schedule is two doses of 0.5 ml on days 0 and 28. Alternatively, a rapid schedule of two doses on days 0 and 7 can be used.",
     "The rapid schedule (days 0 and 7) is licensed for adults aged 18 to 64 years, and antibody responses are non-inferior to those of the standard schedule.",
     "The rapid schedule may be used in all age groups from two months of age where there is genuinely insufficient time to complete the standard schedule before travel. It is off license for children from two months to 17 years of age and for adults aged 65 years and older because of lack of data, but there are no data to suggest that the rapid schedule would be harmful for these travellers.",
     "With both schedules, primary immunisation should ideally be completed at least one week prior to potential exposure to JE virus.",
     "In situations where the primary course plus initial booster has been interrupted, the schedule should be resumed and not restarted.",
     "First booster for children (from two months) and adults under 65 years: for those at ongoing risk (such as laboratory staff and long-term travellers who expect to reside in JE endemic areas for appreciable periods of time) a booster dose should be given 12 months after primary immunisation; for other travellers a booster dose should be given within 12 to 24 months after primary immunisation, prior to potential re-exposure to JE virus.",
     "First booster for adults aged 65 years and older: the duration of protection from the primary course is uncertain, and a booster dose at 12 months should be considered for those at continued or further risk.",
     "Second booster for adults aged 18 to 64 years: a second booster dose (fourth dose) should be offered at 10 years to those who remain at risk.",
     "Second booster for children: no long-term seroprotection data beyond three years after the first booster have been generated. One study in children living in a risk area estimated the duration of protection to be 9 years after the first booster dose, and no studies were identified estimating length of protection in those living outside risk areas.",
     "Second booster for adults aged 65 years and older: the length of protection following the booster (third) dose is not known; response to the vaccine may be reduced in this age group and immunity may wane before 10 years.",
     "IXIARO may be used as a booster for those who previously received Green Cross vaccine or Biken vaccine.",
     "IXIARO should be given by intramuscular injection. For individuals who have a bleeding disorder it should be given by deep subcutaneous injection to reduce the risk of bleeding.",
     "IXIARO can be given at the same time as other travel or routine vaccines. The vaccines should be given at a separate site, preferably in a different limb; if given in the same limb they should be at least 2.5 cm apart.",
     "Equipment used for vaccination, including used vials, ampoules or partially discharged vaccines, should be disposed of at the end of a session by sealing in a proper puncture-resistant sharps box according to local authority regulations and Health Technical Memorandum 07-01.",
     "IXIARO is available from Valneva UK Ltd.",
   ]),
   ("Contraindications and precautions", [
     "There are very few individuals who cannot receive IXIARO. When there is doubt, appropriate advice should be sought from a travel health specialist.",
     "IXIARO should not be given to those who have had a confirmed anaphylactic or serious systemic reaction to a previous dose of IXIARO vaccine.",
     "IXIARO should not be given to those who have had a confirmed anaphylactic reaction to any component of the vaccine.",
     "Individuals with pre-existing allergies: there is no known extra risk of hypersensitivity reactions to the IXIARO vaccine.",
     "Bleeding disorders: IXIARO should be given by deep subcutaneous injection rather than intramuscularly to reduce the risk of bleeding.",
   ]),
   ("Pregnancy and breastfeeding", [
     "As a precautionary measure, administration of IXIARO during pregnancy or lactation should be avoided.",
     "However, travellers and their medical advisers must make a risk assessment of the theoretical risks of JE vaccine in pregnancy against the potential risk of acquiring JE.",
     "Miscarriage has been associated with JE virus infection when acquired in the first two trimesters of pregnancy.",
   ]),
   ("Adverse reactions", [
     "The most common adverse reactions observed after administration of IXIARO are pain and tenderness at the injection site, headache, fatigue and myalgia.",
     "Other commonly reported reactions are erythema, hardening, swelling and itching at the injection site, influenza-like illness, pyrexia and nausea.",
   ]),
   ("Storage", [
     "Vaccines should be stored in the original packaging at +2 degrees C to +8 degrees C and protected from light.",
     "All vaccines are sensitive to some extent to heat and cold. Heat speeds up the decline in potency of most vaccines, reducing their shelf life, and effectiveness cannot be guaranteed unless vaccines have been stored at the correct temperature.",
     "Freezing may cause increased reactogenicity and loss of potency for some vaccines, and can cause hairline cracks in the container leading to contamination of the contents.",
   ]),
   ("What this chapter does not state", [
     "The chapter does not state a post-vaccination observation period after IXIARO is given.",
     "The chapter does not state that adrenaline must be available at the time of vaccination, and it does not refer to the management of anaphylaxis.",
     "The chapter does not specify an injection site or needle size for the intramuscular dose; it states only that IXIARO should be given by intramuscular injection (or by deep subcutaneous injection for those with a bleeding disorder) and that co-administered vaccines should be given at separate sites.",
     "The chapter does not state a minimum interval between the second primary dose and the first booster other than the 12 month and 12 to 24 month timings given above, and it does not give any guidance on immunosuppressed individuals.",
   ]),
  ],
 },
}
